Repository apache/echarts, pull requests merged in 2019-10, with the labels that each got.

#11324 Add log axis for radar charts
  CONTRIBUTING.md
  src/coord/radar/Radar.js
  src/coord/radar/RadarModel.js
Labels: PR: awaiting review

#11285 new feature Fix9215 add event ''brushEnd"
  src/component/brush/BrushView.js
  src/component/brush/brushAction.js
Labels: PR: awaiting review

#11186 FIX #11176 xAxis.axisTick.interval appears different between echart4 and echart3.8
  src/coord/Axis.js
  test/axis-interval.html
Labels: PR: awaiting review

#11429 style: fix formatting style of #11186
  src/coord/Axis.js
  test/axis-interval.html
Labels: PR: author is committer, PR: awaiting review

#11393 feat: support round cap for polar bars
  src/chart/bar/BarSeries.js
  src/chart/bar/BarView.js
  src/component/axis/AngleAxisView.js
  src/coord/polar/polarCreator.js
  src/layout/barPolar.js
  src/util/graphic.js
  src/util/symbol.js
  test/polar-rounded.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/polar-rounded.json
Labels: PR: author is committer, PR: awaiting review

#11430 ci: use GitHub ci
  .github/workflows/nodejs.yml
  .travis.yml
Labels: PR: author is committer, PR: awaiting review

#11373 fix(gauge): update data with dataset #10945
  src/chart/gauge/GaugeSeries.js
  test/gauge-simple.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/gauge-simple.json
Labels: PR: author is committer, PR: awaiting review

#11453 refactor(polar): fix circular dependency
  src/chart/bar/BarView.js
  src/util/graphic.js
  src/util/shape/sausage.js
  src/util/symbol.js
  test/polar-rounded.html
Labels: PR: author is committer, PR: awaiting review

#11448 chore: tweak test case and tweak the patch of #11186
  src/coord/Axis.js
  test/axis-interval.html
Labels: PR: please merge

#11445 fix-11422 关系图边增加forceIgnore属性，不参加节点位置计算
  src/chart/graph/forceHelper.js
  src/chart/graph/forceLayout.js
  src/chart/helper/createGraphFromNodeEdge.js
  src/data/Graph.js
  test/force-edge-ignoreLayout.html
Labels: PR: awaiting review

#11456 fix(toolbox): avoid text overflow when mouseon #10951
  src/component/toolbox/ToolboxView.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/toolbox-title.json
  test/toolbox-title.html
Labels: PR: author is committer, PR: awaiting review

#11479 fix(time): bar bandWidth with time axis #11145
  src/layout/barGrid.js
  test/bar2.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/bar2.json
Labels: PR: author is committer, PR: awaiting review

#11514 fix(axis): fix extra ticks added caused by rounding error. add test cases for splitArea
  src/coord/Axis.js
  test/axis-splitArea.html
Labels: PR: author is committer
