Repository apache/echarts, pull requests merged in 2019-12, with the labels that each got.

#11737 fix(legend): legend of pie/funnel/radar can pick from visualMap encoded color
  src/chart/funnel/FunnelSeries.js
  src/chart/graph/GraphSeries.js
  src/chart/pie/PieSeries.js
  src/chart/radar/RadarSeries.js
  src/chart/themeRiver/ThemeRiverSeries.js
  src/component/legend/LegendModel.js
  src/component/legend/LegendView.js
  src/model/Series.js
  src/visual/LegendVisualProvider.js
  src/visual/dataColor.js
  test/legend-visualMapColor.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/legend-visualMapColor.json
Labels: PR: author is committer, PR: awaiting review

#11711 Test framework changed to jest and cases run in node environment
  .gitignore
  package-lock.json
  package.json
  test/ut/configure
  test/ut/core/setup.js
  test/ut/core/uiHelper.js
  test/ut/core/utHelper.js
  test/ut/jest.config.js
  test/ut/lib/canteen.js
  test/ut/lib/imagediff.js
  test/ut/lib/jasmine-2.3.4/boot.js
  test/ut/lib/jasmine-2.3.4/jasmine-html.js
  test/ut/lib/jasmine-2.3.4/jasmine.css
  test/ut/lib/jasmine-2.3.4/jasmine.js
  test/ut/lib/jasmine-2.3.4/jasmine_favicon.png
  test/ut/spec/api/containPixel.test.js
  test/ut/spec/api/converter.test.js
  test/ut/spec/api/getVisual.test.js
  test/ut/spec/component/dataZoom/helper.test.js
  test/ut/spec/component/graphic/setOption.test.js
  test/ut/spec/component/helper/sliderMove.test.js
  test/ut/spec/component/visualMap/setOption.test.js
  test/ut/spec/data/List.test.js
  test/ut/spec/data/completeDimensions.test.js
  test/ut/spec/model/Component.test.js
  test/ut/spec/model/Global.test.js
  test/ut/spec/model/timelineOptions.test.js
  test/ut/spec/scale/interval.test.js
  test/ut/spec/ui/axis.boundaryGap.js
  test/ut/spec/ui/legend.js
  test/ut/spec/ui/series.bar.js
  test/ut/spec/ui/title.js
  test/ut/spec/ui/title.subtextStyle.js
  test/ut/spec/ui/title.textStyle.js
  test/ut/spec/util/graphic.test.js
  test/ut/spec/util/layout.test.js
  test/ut/spec/util/model.test.js
  test/ut/spec/util/number.test.js
  test/ut/ui.html
  test/ut/ut.html
Labels: PR: author is committer, PR: awaiting review

#11808 Add polyline edge layout for the tree series #7090
  src/chart/tree/TreeSeries.js
  src/chart/tree/TreeView.js
  test/tree-addNode.html
  test/tree-polyline.html
  test/tree-recurrentRemoveNode.html
  test/tree-removeNode.html
Labels: PR: awaiting review

#11941 add tianjin js file. related to #10489
  map/js/province/tianjin.js
Labels: waiting-for: community

#11934 fix https://github.com/apache/incubator-echarts/issues/11658
  src/chart/pie/PieView.js
Labels: waiting-for: community

#11952 fix bug #11610 pagination disappear
  src/component/legend/ScrollableLegendView.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/legend.json
Labels: PR: author is committer, PR: awaiting review

#11956 fix(map): fix slice is not defined error on typed array. #11451
  src/component/helper/MapDraw.js
Labels: PR: author is committer, PR: awaiting review
