Repository apache/echarts, pull requests merged in 2020-10, with the labels that each got.

#13378 [5.0] [Feature] pie series supports cornerRadius & innerCornerRadius.
  src/chart/pie/PieSeries.ts
  src/chart/pie/pieLayout.ts
  test/pie-cornerRadius.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/S

#13390 [5.0] [Feature] sunburst series supports cornerRadius
  src/chart/sunburst/SunburstSeries.ts
  src/chart/sunburst/sunburstLayout.ts
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/S

#13383 feat(tooltip): allow adding classes to tooltip DOM and migrate changes to next branch in #12834.
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipModel.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
  test/tooltip-windowResize.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/M

#13372 fix(toolbox): fix the bug of overriding title when click the stack button
  src/component/toolbox/feature/MagicType.ts
  test/runTest/actions/toolbox-stack-custom.json
  test/toolbox-stack-custom.html
Labels: PR: awaiting review, size/S

#13398 fix(tooltip): fix some issues in new tooltip.
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13432 fix(extension/bmap): fix bmap first layout may be incorrect if container's layout is flex or grid.(#13424)
  extension-src/bmap/BMapCoordSys.ts
  extension-src/bmap/BMapView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13170 feat(dirty-rect): Using dirty rectangles to render charts
  src/echarts.ts
  test/lib/caseFrame.css
  test/lib/caseFrame.js
  test/lib/config.js
Labels: PR: author is committer, PR: awaiting review, size/S

#13416 feat(gauge): modify some default values, support svg pointer, add axisLine.distance/splitLine.distance/progress/anchor/data[i].title/data[i].detail #13216
  src/chart/gauge/GaugeSeries.ts
  src/chart/gauge/GaugeView.ts
  src/label/LabelManager.ts
  src/theme/dark.ts
  test/gauge-distance.html
  test/gauge-group-title-detail.html
  test/gauge-pointer.html
  test/gauge-progress.html
  test/gauge-simple.html
  test/gauge.html
  test/runTest/actions/gauge-distance.json
  test/runTest/actions/gauge-group-title-detail.json
  test/runTest/actions/gauge-pointer.json
  test/runTest/actions/gauge-progress.json
  test/runTest/actions/gauge.json
Labels: PR: author is committer, PR: awaiting review, size/XL

#13443 Fix(legend.scroll): scroll animation start position was incorrect
  src/component/legend/ScrollableLegendView.ts
  test/legend-scroll2plain.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13382 fix(tooltip): hide tooltip when mouse leaves the chart(#12778)
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13468 Custom morph2
  src/chart/boxplot/boxplotTransform.ts
  src/chart/custom.ts
  src/component/transform/filterTransform.ts
  src/component/transform/sortTransform.ts
  src/coord/cartesian/Grid.ts
  src/coord/scaleRawExtentInfo.ts
  src/data/DataDiffer.ts
  src/data/List.ts
  src/data/Source.ts
  src/data/helper/dataProvider.ts
  src/data/helper/sourceHelper.ts
  src/data/helper/sourceManager.ts
  src/data/helper/transform.ts
  src/echarts.ts
  src/model/Global.ts
  src/model/OptionManager.ts
  src/model/Series.ts
  src/stream/Scheduler.ts
  src/stream/task.ts
  src/util/graphic.ts
  src/util/model.ts
  src/util/types.ts
  test/custom-shape-morphing2.html
  test/custom-shape-morphing3.html
  test/data-transform-ecStat.html
  test/lib/config.js
  test/lib/ecStatTransform.js
  test/lib/myTransform/aggregate.js
  test/lib/myTransform/id.js
  test/lib/transitionPlayer.js
  test/ut/spec/data/List.test.ts
Labels: size/XXL

#13470 add: Japanese i18n file
  src/i18n/langJA.ts
Labels: size/L

#13469 Allow passing of DOM nodes to setContent
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
  src/util/types.ts
  test/tooltip-domnode.html
Labels: size/M

#13501 fix(line): only bolder when line width in normal state is larger than 0.
  src/chart/line/LineView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13490 feat(decal): using "none" to disable decal
  src/util/decal.ts
  src/util/types.ts
  test/decal.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/S

#13506 test: Fix outdated recorded interactions in visual regression tests
  src/chart/line/LineView.ts
  src/util/states.ts
  test/custom-hexbin.html
  test/graph.html
  test/hoverStyle.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/appendData.json
  test/runTest/actions/axis-interval2.json
  test/runTest/actions/brush.json
  test/runTest/actions/calendar-month.json
  test/runTest/actions/clip.json
  test/runTest/actions/color-mix-aqi.json
  test/runTest/actions/connect-dynamic.json
  test/runTest/actions/connect.json
  test/runTest/actions/connect2.json
  test/runTest/actions/custom-hexbin.json
  test/runTest/actions/dataZoom-action.json
  test/runTest/actions/dataZoom-axes.json
  test/runTest/actions/dataZoom-rainfall.json
  test/runTest/actions/dataZoom-scatter-hv.json
  test/runTest/actions/dataZoom-toolbox.json
  test/runTest/actions/geo-map.json
  test/runTest/actions/getOption.json
  test/runTest/actions/heatmap.json
  test/runTest/actions/homepage3.json
  test/runTest/actions/hoverStyle.json
  test/runTest/actions/legend.json
  test/runTest/actions/mapWorld.json
  test/runTest/actions/markArea.json
  test/runTest/actions/pie-calculable.json
  test/runTest/actions/scatter-single-axis.json
  test/runTest/client/client.js
  test/runTest/server.js
Labels: PR: author is committer, PR: awaiting review, size/S

#13507 Fix locale params incorrect in timeline.
  src/component/dataZoom/DataZoomModel.ts
  src/component/timeline/SliderTimelineView.ts
  src/scale/Interval.ts
  src/scale/Ordinal.ts
  src/scale/Scale.ts
  src/scale/Time.ts
  src/util/types.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#13510 test: add more recorded interactions.
  test/browser-esm.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/dataSelect.json
  test/runTest/actions/decal.json
  test/runTest/actions/funnel.json
  test/runTest/actions/hoverFocus.json
  test/runTest/actions/hoverFocus2.json
  test/runTest/actions/label-layout.json
  test/runTest/actions/line-boldWhenHover.json
  test/runTest/actions/pie-label-extreme.json
  test/runTest/recorder/recorder.js
  test/visualMap-continuous.html
Labels: PR: author is committer, PR: awaiting review, size/XS
