Repository apache/echarts, pull requests merged in 2020-12, with the labels that each got.

#13742 fix(decal): fix types and improve test cases
  src/util/types.ts
  test/aria-line-bar.html
  test/aria-pie.html
  test/decal.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13774 fix: [decals] the path of fetching global decals in treemap.
  src/chart/treemap/TreemapSeries.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13793 fix(typo): fix comment typo
  src/coord/axisHelper.ts
Labels: size/S

#13792 Fix: label text animation issues.
  src/chart/helper/labelHelper.ts
  src/chart/sankey/SankeySeries.ts
  src/data/helper/dataProvider.ts
  src/label/labelStyle.ts
  src/model/mixin/dataFormat.ts
  src/util/model.ts
  src/util/types.ts
  test/label-animation.html
  test/lib/testHelper.js
  test/line-endLabel.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/label-animation.json
  test/runTest/actions/line-endLabel.json
Labels: PR: author is committer, PR: awaiting review, size/M

#13771 Fix(tooltip.borderColor): consider tooltipModel borderColor
  src/component/tooltip/TooltipModel.ts
  src/component/tooltip/TooltipView.ts
  test/new-tooltip.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13816 fix: fix code brought in #13771
  src/component/tooltip/TooltipView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13817 fix: fix that label animation restart when bar realtimeSort change bar orders.
  src/label/labelStyle.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13822 fix(bar-race): fix default categorySortInfo value bug
  src/coord/cartesian/AxisModel.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13823 fix(types): add missing `number` type for line series `smooth`.(#13815)
  src/chart/line/LineSeries.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13732 fix(svg): fix chart cannot be exported with SVG renderer in IE.
  src/component/toolbox/feature/SaveAsImage.ts
  test/ie-svg-export.html
Labels: PR: author is committer, PR: awaiting review, size/M

#13863 chore: update keywords, description, homepage information and add bugs field in package.json.
  .asf.yaml
  package.json
Labels: PR: author is committer, PR: awaiting review, size/S

#13885 Fix typo in comment
  src/data/List.ts
Labels: PR: awaiting review, size/XS

#13916 fix: fix candlestick color to 5.0 theme
  src/chart/candlestick/CandlestickSeries.ts
  src/theme/dark.ts
Labels: PR: author is committer, PR: awaiting review, size/S
