Repository apache/echarts, pull requests merged in 2020-11, with the labels that each got.

#13523 fix(theme): fix deprecated usage.(#13519)
  src/theme/dark.ts
  theme/dark-blue.js
  theme/dark-bold.js
  theme/dark-digerati.js
  theme/dark-fresh-cut.js
  theme/dark-mushroom.js
  theme/dark.js
  theme/infographic.js
  theme/macarons2.js
  theme/shine.js
Labels: PR: author is committer, PR: awaiting review, size/L

#13522 Fix treemap click bug when animation not finished and state animation triggered.
  src/chart/treemap/TreemapView.ts
  src/util/animation.ts
  test/treemap-option.html
Labels: PR: author is committer, PR: awaiting review, size/L

#13521 Support decal in custom series, and fix some decal implementations.
  src/chart/custom.ts
  src/chart/helper/enableAriaDecalForTree.ts
  src/chart/sankey/SankeySeries.ts
  src/chart/treemap/TreemapView.ts
  src/component/aria.ts
  src/coord/parallel/AxisModel.ts
  src/data/List.ts
  src/model/Global.ts
  src/model/Series.ts
  src/model/globalDefault.ts
  src/model/mixin/areaStyle.ts
  src/model/mixin/itemStyle.ts
  src/model/mixin/lineStyle.ts
  src/model/mixin/palette.ts
  src/util/types.ts
  src/visual/aria.ts
  src/visual/style.ts
  test/decal.html
  test/ut/jest.config.js
  test/ut/spec/component/graphic/setOption.test.ts
  test/ut/spec/series/custom.test.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13525 fix(test): fix some issues in `pie-cornerRadius` test case.
  test/pie-cornerRadius.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13553 fix: [graph] circular layout should be able to base on symbolSize.
  src/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13554 fix: [parallel] fix that the second category parallel axis can not be selectable
  src/model/referHelper.ts
  test/parallel-feature.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13556 fix: [geo select state] fix that dispatchAction({ type: 'geoToggleSelect', ... }) now work immediately.
  src/component/geo/GeoView.ts
  src/echarts.ts
  src/util/types.ts
  test/hoverStyle.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13558 feat(decal): symbol support array
  src/util/decal.ts
  src/util/types.ts
  test/decal.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/M

#13561 fix: lazyMode should wake zrender up, otherwise will be nothing rendered
  src/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13564 fix: fix symbolRotation not work.
  src/chart/helper/Line.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13566 fix: pictorialBar by default do not "hoverAnimation".
  src/chart/bar/PictorialBarSeries.ts
  src/chart/bar/PictorialBarView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13567 fix: fix parallel select opacity should be applied.
  src/chart/parallel.ts
  src/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13568 fix: markLine (horizontal or vertical) should be displayed after this optimization.
  src/coord/cartesian/Cartesian2D.ts
  test/timeline-layout.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13569 fix: [dataZoom] remove duplicated declaration (test case: test/stream-filter2.html)
  src/component/dataZoom/DataZoomModel.ts
  test/dataZoom-feature.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13572 fix: fix timeline tick symbol displayed at wrong place.
  src/component/timeline/SliderTimelineView.ts
  test/timeline-layout.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13573 chore: add tslib in dependencies
  package.json
Labels: PR: author is committer, PR: awaiting review, size/XS

#13574 fix: [tooltip] add back the missing v4.9 feature: tooltip text shadow.
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipRichContent.ts
  test/tooltip-textStyle.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13576 chore: add missing license description
  src/label/labelStyle.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13570 Fix/use UTC and tooltip.formatter on time axis
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/tooltipMarkup.ts
  src/scale/Time.ts
  src/util/format.ts
  src/util/time.ts
  test/timeZone.html
Labels: PR: author is committer, PR: awaiting review, size/L

#13577 fix: [dataZoom] fix that after dataZoom updated by others (like inside dataZoom), the brush rect does not display.
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13579 Fix animation issues of tree
  src/chart/tree/TreeView.ts
  src/util/graphic.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13586 fix(types): fix wrong and missed types.
  src/chart/bar/BarSeries.ts
  src/chart/bar/BaseBarSeries.ts
  src/chart/bar/PictorialBarSeries.ts
  src/chart/boxplot/BoxplotSeries.ts
  src/chart/candlestick/CandlestickSeries.ts
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/funnel/FunnelSeries.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/graph/GraphSeries.ts
  src/chart/heatmap/HeatmapSeries.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/line/LineSeries.ts
  src/chart/lines/LinesSeries.ts
  src/chart/map/MapSeries.ts
  src/chart/parallel/ParallelSeries.ts
  src/chart/pie/PieSeries.ts
  src/chart/radar/RadarSeries.ts
  src/chart/sankey/SankeySeries.ts
  src/chart/scatter/ScatterSeries.ts
  src/chart/sunburst/SunburstSeries.ts
  src/chart/sunburst/sunburstLayout.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/tree/TreeSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/brush/BrushModel.ts
  src/component/marker/MarkAreaModel.ts
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkPointModel.ts
  src/component/timeline/TimelineModel.ts
  src/coord/axisCommonTypes.ts
  src/coord/parallel/AxisModel.ts
  src/util/types.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13587 fix(tree): make same animation config in update and remove.
  src/chart/tree/TreeView.ts
  src/util/graphic.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#13580 Fix(tree): `symbol` is `none` cannot be skipped
  src/chart/tree/TreeView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13590 fix(decal): symbolKeepAspect was not working
  src/util/decal.ts
  test/decal.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#13589 fix(label): inherit opacity from attached element
  src/chart/bar/BarView.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/funnel/FunnelView.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/chart/pie/PieView.ts
  src/chart/radar/RadarView.ts
  src/chart/tree/TreeView.ts
  src/chart/treemap/TreemapView.ts
  src/label/LabelManager.ts
  src/label/labelStyle.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13591 fix(label): inheritOpacity should not been applied in rich when opacity in top is given.
  src/chart/bar/BarView.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/funnel/FunnelView.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/chart/pie/PieView.ts
  src/chart/radar/RadarView.ts
  src/chart/treemap/TreemapView.ts
  src/label/labelStyle.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#13596 Release 5.0.0
  .npmignore
  package-lock.json
  package.json
Labels: PR: author is committer, PR: awaiting review, size/XS

#13597 fix: add license and fix addHeader script.
  .asf.yaml
  .eslintrc-common.yaml
  .headerignore
  .lgtm.yml
  build/addHeader.js
  build/build-i18n.js
  build/dev-fast.js
  build/preamble.js
  build/testDts.js
  extension-src/.eslintrc.yaml
  src/.eslintrc.yaml
  src/chart/helper/enableAriaDecalForTree.ts
  src/util/decal.ts
  src/util/states.ts
  test/custom-transition-texture.js
  test/ut/.eslintrc.yaml
Labels: PR: author is committer, PR: awaiting review, size/L

#13600 fix: ensure folder exist for i18n build.
  build/build-i18n.js
Labels: PR: author is committer, PR: awaiting review, size/XS

#13612 fix(time): fix default time axis formatter
  src/util/time.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13629 fix(build): fix some compatibility issues of build scripts in Windows.
  build/config.js
  build/pre-publish.js
  build/release.js
  src/util/time.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13646 fix(decal): remove unused dashLineOffset
  src/model/globalDefault.ts
  src/util/decal.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13648 Fix/aggregate
  build/build.js
  build/config.js
  src/data/helper/transform.ts
  test/custom-shape-morphing2.html
  test/custom-shape-morphing3.html
  test/data-transform-aggregate.html
  test/lib/config.js
  test/lib/myTransform/aggregate.js
  test/lib/myTransform/dist/myTransform.js
  test/lib/myTransform/dist/myTransform.js.map
  test/lib/myTransform/id.js
  test/lib/myTransform/src/.eslintrc.yaml
  test/lib/myTransform/src/aggregate.ts
  test/lib/myTransform/src/id.ts
  test/lib/myTransform/src/index.ts
  tsconfig.json
Labels: PR: author is committer, PR: awaiting review, size/M

#13653 fix: fix NPE when click an area in geo map.
  src/component/geo/GeoView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13660 fix outdated links
  extension-src/bmap/README.md
  test/bar-t.html
  test/dataZoom-axes.html
  test/graphicOption.html
  test/lines-ny-appendData.html
  test/tooltip-touch.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13705 doc: update description
  .asf.yaml
Labels: PR: author is committer, PR: awaiting review, size/XS
