Repository apache/echarts, pull requests merged in 2020-03, with the labels that each got.

#12215 Feat: use auto calculate if min /max is null
  src/coord/axisHelper.js
  src/echarts.js
  test/axis-extrema.html
Labels: PR: author is committer, PR: awaiting review

#11718 fix(Series): check null pointer
  src/model/Series.js
Labels: PR: awaiting review, waiting-for: community

#12331 Fix: barBorderRadius didn't work
  src/chart/bar/BarView.js
  test/bar-background.html
Labels: PR: author is committer, PR: awaiting review

#12342 fix(heatmap): 1px gap between rect
  src/chart/heatmap/HeatmapView.js
  test/heatmap-gap-bug.html
Labels: PR: author is committer, PR: awaiting review

#12340 fix(map): map animation when zoom and center change. fix #11947
  src/component/helper/MapDraw.js
  test/map.html
Labels: PR: author is committer, PR: awaiting review

#12348 feat(scatter): make `symbolRotate` functional for scatter series. close #12347.
  src/chart/helper/Symbol.js
  src/visual/symbol.js
  test/symbol3.html
Labels: PR: awaiting review

#12354 fix(effectScatter): the ripple effect of effectScatter does not rotate as the rotation of scatter symbol when using functional `symbolRotate`. close #12353.
  src/chart/helper/EffectSymbol.js
  test/effectScatter2.html
Labels: PR: awaiting review
