Repository apache/echarts, pull requests merged in 2020-09, with the labels that each got.

#13271 [5.0] [Feature] Bring shape morphing ability in custom series
  src/chart/custom.ts
  test/custom-hexbin.html
  test/custom-shape-morphing.html
  test/data/usa.json
  test/map-nameProperty.html
Labels: PR: author is committer, PR: awaiting review

#13283 fix: partially resolves #13164
  src/echarts.js
Labels: PR: awaiting review, size/XS

#13315 german translation added
  i18n/langDE-obj.js
  i18n/langDE.js
  src/i18n/langDE.ts
Labels: PR: awaiting review, size/L

#13214 chore(extension/bmap): migrate changes to next branch and fix a bug brought by a typo.(#13213)
  extension-src/bmap/BMapCoordSys.ts
  extension-src/bmap/BMapModel.ts
  extension-src/bmap/BMapView.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#13338 github add tags
  .asf.yaml
Labels: PR: author is committer, PR: awaiting review, size/S

#13337 [5.0] [Feature] support largest-triangle-three-buckets based on 13317
  src/chart/helper/createRenderPlanner.ts
  src/chart/line/LineSeries.ts
  src/data/List.ts
  src/model/Series.ts
  src/processor/dataSample.ts
  src/util/types.ts
  test/data/large-data.json
  test/sample-compare.html
Labels: PR: author is committer, PR: awaiting review

#13339 [5.0] [Performance] Remove chunk in List storage
  src/chart/line/poly.ts
  src/data/List.ts
  src/data/helper/dataProvider.ts
  src/processor/dataSample.ts
  test/sample-compare.html
Labels: PR: author is committer, PR: awaiting review, size/XL

#13246 feat(line): endLabel animation
  src/chart/bar/BarView.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/helper/createClipPathFromCoordSys.ts
  src/chart/helper/labelHelper.ts
  src/chart/line/LineSeries.ts
  src/chart/line/LineView.ts
  src/chart/line/poly.ts
  src/data/List.ts
  src/label/labelStyle.ts
  src/util/graphic.ts
  src/util/model.ts
  src/util/states.ts
  src/util/types.ts
  test/bar-race.html
  test/line-animation.html
  test/line-endLabel.html
  test/polarLine.html
Labels: PR: awaiting doc, PR: awaiting review, size/XL

#13369 feat: LGTM security analysis
  .lgtm.yml
Labels: PR: awaiting review, size/S
