Repository apache/echarts, pull requests merged in 2020-08, with the labels that each got.

#13070 fix(util/styleCompat): fix a typo in `convertToEC4RichItem` function.
  src/util/styleCompat.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#12556 fix(axisLabel): fix axisLabel rotating with grid.containLabel #12259
  src/coord/axisHelper.js
  test/axisLabel.html
Labels: PR: awaiting review

#12558 fix(bmap): bmap event `moveend` is always triggered when dragging or zoomend.
  extension-src/bmap/BMapCoordSys.js
  extension-src/bmap/BMapView.js
  test/bmap2.html
Labels: PR: author is committer, PR: awaiting review

#12850 fix(lines): lines series shouldn't disappear after `setOption({})`. (#12836)
  src/chart/lines/LinesSeries.js
  test/lines-mergeOption.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#11849 Fix dataview show NaN when user use dataset
  src/component/toolbox/feature/DataView.js
  test/dataset-charts.html
Labels: PR: author is committer, PR: awaiting review

#12561 fix(pie): pie series render incorrectly after editing its data in DataView. close #12560.
  src/component/toolbox/feature/DataView.js
  test/pie-dataView.html
Labels: PR: author is committer, PR: awaiting review, size/S

#12550 feat(dataZoom): custom brush style in toolbox.feature.dataZoom
  src/component/toolbox/feature/DataZoom.js
  test/dataZoom-toolbox.html
Labels: PR: awaiting review, size/S

#12664 fix(tooltip): richText for series-specific formatters #12232
  src/chart/map/MapSeries.js
  src/chart/radar/RadarSeries.js
  src/component/marker/MarkerModel.js
  src/component/tooltip/TooltipContent.js
  src/component/tooltip/TooltipRichContent.js
  test/tooltip-textStyle.html
Labels: PR: author is committer, PR: awaiting review

#12669 fix(markArea): hide labels when markArea is not inside grid #12591
  src/component/marker/MarkAreaView.js
  test/markArea.html
Labels: PR: author is committer, PR: awaiting review, size/M

#13067 Optimize: disable tooltip transition at first show
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#12022 fix(themeRiver): use layer key map rather then largestLayer #11948
  src/chart/themeRiver/ThemeRiverSeries.js
  test/themeRiver3.html
Labels: PR: awaiting review, priority: high, size/M

#12754 feat(funnel): funnel chart support orient API
  src/chart/funnel/FunnelSeries.js
  src/chart/funnel/funnelLayout.js
  test/funnel.html
Labels: PR: awaiting review

#13079 fix(graph): fix null pointer error in graph simple layout
  src/chart/graph/simpleLayout.js
Labels: PR: author is committer, PR: awaiting review, size/XS

#13080 fix: recover auto rotation for line symbol.
  src/chart/helper/Line.js
  test/markLine-symbolRotate.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13084 fix(bar): showBackground bug when update with no previous background elements
  src/chart/bar/BarView.js
Labels: PR: awaiting review, size/M

#13085 fix(bar): showBackground bug when update with no previous background elements
  src/chart/bar/BarView.js
Labels: size/XS

#13087 fix(timeline): fix icon style not work bug brought in #13015
  src/component/timeline/SliderTimelineView.js
Labels: size/XS

#13088 style: remove unexpected es6 code
  src/component/timeline/SliderTimelineView.js
Labels: size/XS

#13117 fix(model/Global): fix a typo.
  src/model/Global.ts
Labels: size/XS

#13121 fix(bar-race): fix bug with animation
  src/chart/bar/BarSeries.ts
  src/chart/bar/BarView.ts
  src/coord/cartesian/AxisModel.ts
  src/util/graphic.ts
  test/bar-race.html
Labels: PR: author is committer, PR: awaiting review

#13127 Dataset trans2
  src/component/transform/sortTransform.ts
  src/data/List.ts
  src/data/helper/dataValueHelper.ts
  src/data/helper/parseDataValue.ts
  src/data/helper/transform.ts
  src/util/conditionalExpression.ts
  src/util/number.ts
  test/data-transform.html
  test/ut/spec/data/completeDimensions.test.js
  test/ut/spec/data/dataValueHelper.test.js
  test/ut/spec/util/number.test.js
Labels: PR: author is committer, PR: awaiting review, size/XL

#13149 doc: update readme
  README.md
Labels: size/XS

#13169 Fix lint problem in next
  package.json
  src/.eslintrc.yaml
  src/component/geo.ts
  src/component/parallel.ts
  src/i18n/langES.ts
  src/i18n/langFI.ts
  src/i18n/langTH.ts
  src/scale/Interval.ts
  src/scale/Ordinal.ts
  src/scale/Scale.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13100 fix(tooltip): keep axis tooltip open on refresh
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, size/XS

#13139 Fix: make `contentToOption` totally optional
  src/component/toolbox/feature/DataView.ts
Labels: PR: awaiting review, size/XS

#12961 feat: more configurable styles for lineStyle & borderStyle.
  src/chart/bar/BarView.ts
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/component/axis/SingleAxisView.ts
  src/component/axisPointer/viewHelper.ts
  src/component/title.ts
  src/label/labelStyle.ts
  src/model/mixin/itemStyle.ts
  src/model/mixin/lineStyle.ts
  src/util/types.ts
  src/visual/style.ts
  test/line-style.html
Labels: PR: author is committer, PR: awaiting review, size/L
