Repository apache/echarts, pull requests merged in 2020-07, with the labels that each got.

#12891 tweak(graph): tweak #12590.
  src/chart/graph/GraphSeries.js
  src/chart/graph/forceLayout.js
  src/chart/helper/createGraphFromNodeEdge.js
  src/chart/helper/multipleGraphEdgeHelper.js
  src/data/Graph.js
Labels: PR: author is committer, PR: awaiting review

#12915 fix(tree) The chart line color is not updated when updating a node's lineStyle
  src/chart/tree/TreeView.js
Labels: PR: awaiting review

#12868 feat(extension/bmap): support for specifying initial map options.
  extension-src/bmap/BMapCoordSys.js
  extension-src/bmap/BMapModel.js
  test/bmap-mapOptions.html
Labels: PR: author is committer, PR: awaiting review

#12921 feat(bot): added .gitattributes file to exclude files needed to ignore for pull-request-size bot.
  .gitattributes
Labels: PR: author is committer, PR: awaiting review, size/XS

#12965 [5.0] feat(animation): action from dataZoom and resize can override the animation in series.
  src/chart/line/LineView.ts
  src/chart/parallel/ParallelView.ts
  src/component/axis/ParallelAxisView.ts
  src/component/axis/parallelAxisAction.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/dataZoom/roams.ts
  src/component/parallel.ts
  src/echarts.ts
  src/model/Global.ts
  src/util/graphic.ts
  src/util/types.ts
Labels: PR: awaiting review, size/L

#12943 Fix: radar model mixin with AxisModelCommonMixin
  src/coord/radar/RadarModel.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#12973 fix: fix email link in README.
  README.md
Labels: PR: author is committer, PR: awaiting review, size/XS

#12987 Remove component
  src/chart/bar/BarView.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/helper/createListFromArray.ts
  src/chart/map/MapSeries.ts
  src/chart/parallel/ParallelSeries.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/axisPointer.ts
  src/component/brush/preprocessor.ts
  src/component/dataZoom/AxisProxy.ts
  src/component/dataZoom/DataZoomModel.ts
  src/component/dataZoom/DataZoomView.ts
  src/component/dataZoom/InsideZoomView.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/dataZoom/dataZoomAction.ts
  src/component/dataZoom/dataZoomProcessor.ts
  src/component/dataZoom/helper.ts
  src/component/dataZoom/roams.ts
  src/component/graphic.ts
  src/component/helper/BrushTargetManager.ts
  src/component/timeline/TimelineModel.ts
  src/component/timeline/timelineAction.ts
  src/component/toolbox/feature/Brush.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/DataZoom.ts
  src/component/toolbox/feature/MagicType.ts
  src/coord/axisModelCommonMixin.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/cartesian/Grid.ts
  src/coord/cartesian/cartesianAxisHelper.ts
  src/coord/geo/Geo.ts
  src/coord/parallel/ParallelModel.ts
  src/coord/parallel/parallelCreator.ts
  src/coord/parallel/parallelPreprocessor.ts
  src/coord/polar/AxisModel.ts
  src/coord/polar/polarCreator.ts
  src/coord/single/singleCreator.ts
  src/echarts.ts
  src/model/Component.ts
  src/model/Global.ts
  src/model/Model.ts
  src/model/OptionManager.ts
  src/model/internalComponentCreator.ts
  src/model/mixin/textStyle.ts
  src/model/referHelper.ts
  src/preprocessor/backwardCompat.ts
  src/util/model.ts
  src/util/types.ts
  test/dataZoom-feature.html
  test/dataZoom-toolbox.html
  test/lib/testHelper.js
  test/option-replaceMerge.html
  test/option-replaceMerge2.html
  test/timeline-dynamic-series.html
  test/timeline-life.html
Labels: PR: author is committer, PR: awaiting review, size/XXL

#12997 fix(dataSample): negative size
  src/processor/dataSample.js
Labels: PR: awaiting review, size/XS

#12991 fix(heatmap) Skip rendering for data out of axis content in heatmap (#12969)
  src/chart/heatmap/HeatmapView.ts
  test/heatmap.html
Labels: PR: awaiting review, size/S

#13008 [FEATURE] [5.0] Improve style of dataZoom, visualMap, timeline components. Bug fixes from next branch
  src/ExtensionAPI.ts
  src/chart/bar/BarView.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/custom.ts
  src/chart/gauge/GaugeView.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/LineDraw.ts
  src/chart/helper/Polyline.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/pie/labelLayout.ts
  src/chart/radar/RadarView.ts
  src/chart/treemap/TreemapView.ts
  src/component/axisPointer/axisTrigger.ts
  src/component/axisPointer/viewHelper.ts
  src/component/dataZoom/SliderZoomModel.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/legend/LegendView.ts
  src/component/timeline/SliderTimelineModel.ts
  src/component/timeline/SliderTimelineView.ts
  src/component/timeline/TimelineModel.ts
  src/component/visualMap/ContinuousModel.ts
  src/component/visualMap/ContinuousView.ts
  src/echarts.ts
  src/label/labelStyle.ts
  src/layout/barGrid.ts
  src/legacy/getTextRect.ts
  src/util/format.ts
  src/util/graphic.ts
  src/util/states.ts
  src/util/symbol.ts
  src/util/types.ts
  test/boxplot.html
  test/timeline-finance.html
  test/visualMap-scatter-symbolSize.html
Labels: PR: awaiting review, size/XXL

#13015 fix(timeline): fix a bug which may bring a crash of browser when using dataURI as icon(#12867).
  src/component/timeline/SliderTimelineView.js
  test/timeline-dynamic-series.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13013 feat: make line bolder when line is in emphasis state, designed by #12931.
  src/chart/line/LineSeries.ts
  src/chart/line/LineView.ts
  src/coord/cartesian/GridModel.ts
  test/line-boldWhenHover.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13025 [5.0] [FEATURE] Add select by brushing in dataZoom
  src/ExtensionAPI.ts
  src/component/dataZoom/SliderZoomModel.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/helper/BrushController.ts
  src/component/visualMap/ContinuousView.ts
  src/echarts.ts
  test/dataZoom-rainfall-inside.html
Labels: PR: author is committer, PR: awaiting review, size/L

#12859 [FEATURE] [5.0] time axis label formatter
  src/component/axisPointer/viewHelper.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/timeline/SliderTimelineView.ts
  src/coord/Axis.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  src/coord/axisHelper.ts
  src/coord/axisTickLabelBuilder.ts
  src/export.ts
  src/lang.ts
  src/langEN.ts
  src/scale/Interval.ts
  src/scale/Log.ts
  src/scale/Ordinal.ts
  src/scale/Scale.ts
  src/scale/Time.ts
  src/util/format.ts
  src/util/time.ts
  src/util/types.ts
  test/timeScale-formatter.html
  test/timeScale.html
Labels: PR: author is committer, PR: awaiting review, size/XL, topic: axis-time

#13039 fix(time): tooltip formatter for time axis
  src/lang.ts
  src/scale/Time.ts
  src/util/format.ts
  src/util/time.ts
  test/timeZone.html
Labels: PR: author is committer, PR: awaiting review, size/M

#13044 fix(util/number): the `parseDate` function failed to parse a date string like `2020-07-29 09:2:5`.
  src/util/number.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#12947 [5.0] New tooltip design
  src/chart/bar/BarView.ts
  src/chart/graph/GraphSeries.ts
  src/chart/lines/LinesSeries.ts
  src/chart/map/MapSeries.ts
  src/chart/radar/RadarSeries.ts
  src/chart/sankey/SankeySeries.ts
  src/chart/sankey/sankeyVisual.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/tree/TreeSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/axisPointer/findPointFromSeries.ts
  src/component/geo/GeoView.ts
  src/component/marker/MarkPointView.ts
  src/component/marker/MarkerModel.ts
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipModel.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
  src/coord/radar/IndicatorAxis.ts
  src/data/List.ts
  src/label/LabelManager.ts
  src/model/Series.ts
  src/model/mixin/dataFormat.ts
  src/util/format.ts
  src/util/types.ts
  test/new-tooltip.html
Labels: PR: author is committer, PR: awaiting review, size/L

#13046 [5.0] [FEATURE] Improve default axis style
  src/chart/treemap/TreemapSeries.ts
  src/component/axis/AxisBuilder.ts
  src/component/axis/CartesianAxisView.ts
  src/component/axisPointer/AxisPointerModel.ts
  src/component/title.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
Labels: PR: awaiting review, size/M

#13047 Aira Separator Update
  src/langEN.ts
Labels: PR: awaiting review, size/XS

#13048 Comment some code
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, size/M

#13038 i18n rebuild
  .eslintignore
  build/build-i18n.js
  build/build.js
  build/config.js
  build/ec-lang-rollup-plugin.js
  build/release.js
  i18n/langEN-obj.js
  i18n/langEN.js
  i18n/langES-obj.js
  i18n/langES.js
  i18n/langFI-obj.js
  i18n/langFI.js
  i18n/langTH-obj.js
  i18n/langTH.js
  i18n/langZH-obj.js
  i18n/langZH.js
  package.json
  src/component/legend/LegendModel.ts
  src/component/timeline/SliderTimelineView.ts
  src/component/toolbox/ToolboxModel.ts
  src/component/toolbox/feature/Brush.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/DataZoom.ts
  src/component/toolbox/feature/MagicType.ts
  src/component/toolbox/feature/Restore.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/component/toolbox/featureManager.ts
  src/coord/axisHelper.ts
  src/echarts.ts
  src/i18n/langEN.ts
  src/i18n/langES.ts
  src/i18n/langFI.ts
  src/i18n/langTH.ts
  src/i18n/langZH.ts
  src/langES.ts
  src/langFI.ts
  src/langTH.ts
  src/locale.ts
  src/model/Global.ts
  src/scale/Time.ts
  src/util/format.ts
  src/util/time.ts
  src/visual/aria.ts
  test/lang.html
Labels: PR: author is committer, PR: awaiting review, size/XXL

#13045 fix(bar-race): label animation
  src/action/changeAxisOrder.ts
  src/chart/bar/BarView.ts
  src/component/axis/AxisBuilder.ts
  src/coord/Axis.ts
  src/coord/cartesian/defaultAxisExtentFromData.ts
  src/scale/Ordinal.ts
  src/scale/Scale.ts
  src/util/graphic.ts
  test/bar-race.html
Labels: PR: author is committer, PR: awaiting review, size/L

#13052 fix(util/time): fix potential bug of parsing date from string in Safari.
  src/util/format.ts
  src/util/time.ts
  test/timeZone.html
Labels: PR: author is committer, PR: awaiting review, size/M

#13055 feat(i18n): add translations of FI/ES/TH for time formatter.
  i18n/langES-obj.js
  i18n/langES.js
  i18n/langFI-obj.js
  i18n/langFI.js
  i18n/langTH-obj.js
  i18n/langTH.js
  src/i18n/langES.ts
  src/i18n/langFI.ts
  src/i18n/langTH.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13056 Add french translation
  i18n/langFR-obj.js
  i18n/langFR.js
  src/i18n/langFR.ts
Labels: PR: awaiting review, size/L

#13063 fix(appendData): wakeUp when appendData
  src/echarts.ts
Labels: PR: awaiting review, size/XS

#13060 Test: update pie3.html
  test/pie3.html
Labels: PR: awaiting review, size/XS

#13066 fix(bar-race): fix interpolation
  src/chart/bar/BarView.ts
  src/util/graphic.ts
Labels: PR: author is committer, PR: awaiting review, size/M
