Repository apache/echarts, pull requests merged in 2020-06, with the labels that each got.

#12742 fix(sunburst): enables label formatter in levels #12223
  src/chart/sunburst/SunburstPiece.js
  src/chart/sunburst/SunburstSeries.js
  src/chart/tree/TreeSeries.js
  src/chart/treemap/TreemapSeries.js
  src/chart/treemap/treemapVisual.js
  src/data/Tree.js
  test/sunburst-visualMap.html
  test/treemap-simple2.html
Labels: PR: author is committer, PR: awaiting review

#12780 fix(bmap): removed ES5 in bmap extension.
  extension-src/bmap/BMapView.js
Labels: PR: awaiting review

#12695 fix(radar): symbolRotate does not work for radar series.
  src/chart/radar/RadarView.js
  test/radar.html
Labels: PR: awaiting review

#12659 feat: provide elapsed time in rendered event
  src/echarts.ts
Labels: PR: author is committer, PR: awaiting review, doc

#12828 Update comments to not use defualt (fixing typo)
  src/chart/bar/PictorialBarSeries.js
  src/chart/treemap/treemapLayout.js
  src/component/axisPointer/axisTrigger.js
  src/component/legend/ScrollableLegendView.js
  src/component/visualMap/VisualMapModel.js
  src/coord/axisDefault.js
  src/data/List.js
  src/visual/VisualMapping.js
Labels: PR: awaiting review

#12832 Extent filtered by other axis
  src/component/dataZoom/AxisProxy.ts
  src/component/dataZoom/DataZoomModel.ts
  src/component/dataZoom/dataZoomProcessor.ts
  src/component/dataZoom/helper.ts
  src/component/gridSimple.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisHelper.ts
  src/coord/axisModelCommonMixin.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/cartesian/Grid.ts
  src/coord/cartesian/cartesianAxisHelper.ts
  src/coord/cartesian/defaultAxisExtentFromData.ts
  src/coord/polar/polarCreator.ts
  src/coord/radar/Radar.ts
  src/coord/scaleRawExtentInfo.ts
  src/data/List.ts
  src/echarts.ts
  src/helper.ts
  src/scale/Scale.ts
  test/axis-filter-extent.html
Labels: PR: author is committer, PR: awaiting review

#12762 fix(geo): label formatter in geo works incorrectly, tweaks #10666 & #8612.
  src/coord/geo/GeoModel.js
  test/geo-labelFormatter.html
Labels: PR: author is committer, PR: awaiting review

#12367 fix(tree): the symbols of image type do not display at the first rendering. close #12279.
  src/chart/helper/Symbol.js
  src/chart/tree/TreeView.js
  test/tree-image2.html
Labels: PR: author is committer, PR: awaiting review

#12842 fix(title): incorrect redirect when sublink is clicked.
  src/component/title.js
Labels: PR: author is committer, PR: awaiting review

#12848 core(ci): only run unit test on master or release branch
  .github/workflows/nodejs.yml
Labels: PR: awaiting review

#12852 ci: run on pr opened or synchronized
  .github/workflows/nodejs.yml
Labels: PR: awaiting review

#12834 fix: #12812
  src/component/tooltip/TooltipContent.js
  src/component/tooltip/TooltipRichContent.js
  src/component/tooltip/TooltipView.js
  test/tooltip-windowResize.html
Labels: PR: awaiting review

#12590 feat(graph): graph support multiple edges, for #6811
  src/chart/graph/GraphSeries.js
  src/chart/graph/circularLayoutHelper.js
  src/chart/graph/forceLayout.js
  src/chart/graph/simpleLayoutHelper.js
  src/chart/helper/createGraphFromNodeEdge.js
  src/chart/helper/multipleGraphEdgeHelper.js
  src/data/Graph.js
  test/graph-mulitple-edges.html
Labels: PR: author is committer, PR: awaiting review
