Repository apache/echarts, pull requests merged in 2021-05, with the labels that each got.

#14860 Update langEN.ts
  src/i18n/langEN.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14862 Enhance visual regression test
  test/force2.html
  test/parallel-aqi.html
  test/parallel-nutrients.html
  test/runTest/cli.js
  test/runTest/client/client.css
  test/runTest/client/client.js
  test/runTest/client/index.html
  test/runTest/genReport.js
  test/runTest/server.js
  test/runTest/store.js
  test/runTest/util.js
Labels: PR: author is committer, PR: awaiting review, size/XS

#14872 chore: enhance the script compatibility in Windows and fix some lint errors.
  package.json
  src/chart/candlestick/candlestickVisual.ts
  src/chart/funnel/FunnelSeries.ts
  src/chart/funnel/FunnelView.ts
  src/chart/helper/Line.ts
  src/chart/line/install.ts
  src/chart/line/lineAnimationDiff.ts
  src/chart/sankey/SankeySeries.ts
  src/component/axis/CartesianAxisView.ts
  src/component/axis/SingleAxisView.ts
  src/component/axisPointer/CartesianAxisPointer.ts
  src/component/axisPointer/PolarAxisPointer.ts
  src/component/axisPointer/SingleAxisPointer.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkerView.ts
  src/component/radar/install.ts
  src/component/timeline/SliderTimelineModel.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/coord/calendar/Calendar.ts
  src/coord/radar/Radar.ts
  src/data/helper/sourceHelper.ts
  src/model/mixin/palette.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#14920 fix(custom): fix progressive rendering in custom series.
  package-lock.json
  package.json
  src/chart/custom/install.ts
  test/build/mktest-tpl.html
  test/custom-bmap-grid.html
  test/custom-large.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/custom-bmap-grid.json
  test/runTest/actions/custom-large.json
  test/runTest/actions/tooltip-axisPointer2.json
  test/tooltip-axisPointer2.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14810 fix(legend): remove unexpected syntax to ensure better compatibility.
  src/component/legend/LegendView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14408 fix(toolbox): the `show` option of customized toolbox button does not work.
  src/component/toolbox/ToolboxView.ts
  test/toolbox-custom.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14775 fix(dataZoom): type fix for startValue and endValue. close #14412
  src/component/dataZoom/AxisProxy.ts
  src/component/dataZoom/DataZoomModel.ts
Labels: PR: awaiting review, PR: first-time contributor, size/S

#14813 fix(clip): line chart will throw an error when `clip` is set as `false`.
  src/chart/line/LineView.ts
  test/clip.html
Labels: PR: author is committer, PR: awaiting review, size/M

#14905 fix(tree): error when running setOption twice with diff data
  src/chart/tree/TreeSeries.ts
  test/tree-setoption-twice.html
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14928 fix(tooltip): use kebab-case in transition property.
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14934 fix: error thrown when resize is called after setOption called with lazyUpdate: true. fix #14846, fix #11395 .
  src/core/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14941 test: fix old esl code in test
  test/toolbox-custom.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14930 fix(treemap): error when running setOption twice with diff data
  src/chart/treemap/TreemapSeries.ts
  test/tree-setOption-twice.html
  test/treemap-setOption-twice.html
Labels: PR: awaiting review

#14876 feat(legend): support legend.symbolRotate and inherit from series by default
  src/chart/custom/install.ts
  src/chart/line/LineSeries.ts
  src/chart/map/MapSeries.ts
  src/chart/map/mapSymbolLayout.ts
  src/component/helper/MapDraw.ts
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  src/component/radar/install.ts
  src/data/List.ts
  src/model/Series.ts
  src/visual/symbol.ts
  test/legend-style.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/L

#14963 test(visual): optimize all tests runs list
  test/runTest/client/client.js
  test/runTest/client/index.html
  test/runTest/store.js
Labels: PR: author is committer, PR: awaiting review, size/XS

#14966 fix(option): check the missing component before merge theme
  src/model/Global.ts
  test/ut/spec/model/componentMissing.test.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14972 fix: When component `tooltip.formatter` is not specified, use a specific default formatter, rather than use global `tooltip.formatter` as default. Fix #14939
  src/component/legend/LegendView.ts
  src/component/tooltip/TooltipView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-component.json
  test/tooltip-component.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14871 fix(types) Export cbs and their parameter types
  src/component/tooltip/TooltipModel.ts
  src/export/all.ts
  src/export/option.ts
  src/util/types.ts
Labels: PR: awaiting review, PR: first-time contributor, size/M

#14957 feat(tree): add tree path info to tooltip
  src/chart/tree/TreeSeries.ts
  test/tree-basic.html
Labels: PR: awaiting review, PR: first-time contributor, size/S

#14977 test: add map test for optimizing small regions.
  package-lock.json
  package.json
  src/coord/geo/fix/nanhai.ts
  src/core/echarts.ts
  src/export/core.ts
  src/util/decal.ts
  test/data/map/json/china-new.json
  test/map-china.html
Labels: PR: author is committer, PR: awaiting review, size/M

#14993 fix(label): ensure the label of the temporary symbol is in front of line and area polygon.
  src/chart/line/LineView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#15011 Fix map/geo click params not correct in some cases and label move abnormally when hover.
  src/component/helper/MapDraw.ts
  src/label/labelStyle.ts
  test/geo-map-features.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/geo-map-features.json
Labels: PR: author is committer, PR: awaiting review, size/M

#15016 fix: [custom series] fix null pointer exception when renderItem returns nothing in progressive rendering.
  src/chart/custom/install.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#15031 fix(tooltip): position callback return type. close #15030
  src/util/types.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS
