Repository apache/echarts, pull requests merged in 2021-08, with the labels that each got.

#15454 support 'convertFromEC4CompatibleStyle' to convert font related attri…
  src/util/styleCompat.ts
Labels: PR: awaiting review, size/XS

#15465 fix 15426:milliseconds format
  src/util/time.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#15487 refactor(types): add some initial configuration types #15486
  src/core/echarts.ts
Labels: PR: awaiting review, PR: first-time contributor, size/S

#15512 fix typos, clarify
  CONTRIBUTING.md
  README.md
Labels: PR: awaiting review, size/S, PR: first-time contributor

#15573 fix(bar): optimize label distance when using round cap
  src/chart/bar/BarView.ts
  src/label/sectorLabel.ts
  test/bar-polar-label.html
Labels: PR: awaiting review, PR: author is committer, size/M

#15588 fix(tooltip): tweak the calculation of tooltip offset to make it look not so near to the target element.
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#15618 Fix lint.
  src/coord/axisModelCommonMixin.ts
  src/data/Graph.ts
  src/data/Tree.ts
  src/label/labelStyle.ts
  src/layout/points.ts
  src/model/Model.ts
  src/util/conditionalExpression.ts
  src/visual/style.ts
Labels: PR: awaiting review, PR: author is committer, size/S
