Repository apache/echarts, pull requests merged in 2021-09, with the labels that each got.

#15655 chore: add nightly publish for next branch
  .asf.yaml
  .github/workflows/nightly-next.yml
  build/prepareNightly.js
Labels: PR: awaiting review, PR: author is committer, size/L

#15599 fix(line): not stop existing expand animation when update.
  src/chart/line/LineView.ts
  test/line-animation.html
Labels: PR: awaiting review, PR: author is committer, size/S

#15583 Fix: time axis overlapped labels
  src/component/axis/AxisBuilder.ts
  src/coord/axisTickLabelBuilder.ts
  src/label/labelLayoutHelper.ts
  src/util/types.ts
Labels: PR: awaiting review, size/M, PR: first-time contributor

#15535 Feat(line): event on whole line
  src/core/echarts.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#15662 Merge master to next
  .asf.yaml
  .github/workflows/nightly-next.yml
  build/prepareNightly.js
  src/chart/line/LineView.ts
  src/component/axis/AxisBuilder.ts
  src/coord/axisTickLabelBuilder.ts
  src/label/labelLayoutHelper.ts
  src/util/types.ts
  test/line-animation.html
Labels: PR: awaiting review, PR: author is committer, size/L

#15665 chore: update stale action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: PR: awaiting review, PR: author is committer, size/M

#15666 chore: fix stale config
  .github/workflows/stale.yml
Labels: PR: awaiting review, PR: author is committer, size/XS

#15669 chore: update stale action period
  .github/workflows/stale.yml
Labels: PR: awaiting review, PR: author is committer, size/XS

#15686 fix: Fix MarkLine/MarkPoint/MarkArea do not work on time axis if input string time format
  src/component/marker/MarkAreaView.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkPointView.ts
  src/component/marker/markerHelper.ts
  test/marker-case.html
Labels: PR: awaiting review, PR: author is committer, size/M

#15696 [fix] [type]: improve option types
  index.d.ts
  src/chart/bar/BarSeries.ts
  src/chart/bar/BaseBarSeries.ts
  src/chart/boxplot/BoxplotSeries.ts
  src/chart/candlestick/CandlestickSeries.ts
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/funnel/FunnelSeries.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/graph/GraphSeries.ts
  src/chart/heatmap/HeatmapSeries.ts
  src/chart/helper/LineDraw.ts
  src/chart/line/LineSeries.ts
  src/chart/lines/LinesSeries.ts
  src/chart/map/MapSeries.ts
  src/chart/parallel/ParallelSeries.ts
  src/chart/parallel/ParallelView.ts
  src/chart/pie/PieSeries.ts
  src/chart/radar/RadarSeries.ts
  src/chart/sankey/SankeySeries.ts
  src/chart/scatter/ScatterSeries.ts
  src/chart/sunburst/SunburstSeries.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/tree/TreeSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/marker/MarkAreaModel.ts
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkPointModel.ts
  src/coord/Axis.ts
  src/coord/AxisBaseModel.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisHelper.ts
  src/coord/axisModelCreator.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/cartesian/Grid.ts
  src/coord/geo/GeoModel.ts
  src/coord/parallel/AxisModel.ts
  src/coord/parallel/Parallel.ts
  src/coord/polar/AxisModel.ts
  src/coord/polar/polarCreator.ts
  src/coord/radar/RadarModel.ts
  src/coord/scaleRawExtentInfo.ts
  src/coord/single/AxisModel.ts
  src/coord/single/Single.ts
  src/data/helper/transform.ts
  src/export/option.ts
  src/label/labelGuideHelper.ts
  src/label/labelStyle.ts
  src/layout/barGrid.ts
  src/scale/Ordinal.ts
  src/util/format.ts
  src/util/types.ts
  test/types/basic.ts
Labels: PR: awaiting review, PR: author is committer, size/XL

#15706 fix(sunburst): radius in levels
  src/chart/sunburst/SunburstSeries.ts
  src/chart/sunburst/sunburstLayout.ts
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/M

#15712 feat(axis): add axisLabel.hideOverlap
  src/component/axis/AxisBuilder.ts
  src/coord/axisCommonTypes.ts
  test/timeScale.html
Labels: PR: awaiting review, PR: author is committer, size/S

#15589 fix(polar): wrong sector clockwise when previous data is 0 #15517
  src/chart/bar/BarView.ts
  src/layout/barPolar.ts
  test/bar-polar-basic.html
  test/bar-polar-clockwise.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/bar-polar-clockwise.json
Labels: PR: awaiting review, PR: author is committer, size/S

#15711 fix(line): soft clipping gradient.
  src/chart/line/LineView.ts
  src/export/core.ts
  test/line-visual2.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-visual2.json
Labels: PR: awaiting review, PR: author is committer, size/M

#15715 test: optimize test cases for visual regression test
  test/line-animation.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#15683 fix(tooltip): tooltip may be lagged and shake in Chrome(with the devtools open) and Firefox.
  src/component/tooltip/TooltipView.ts
  test/tooltip-lag-glitch.html
Labels: PR: awaiting review, PR: author is committer, size/S

#15722 Adding pt-BR (Portuguese, Brazil) lang file
  src/i18n/langPT-br.ts
Labels: PR: awaiting review, size/L, PR: first-time contributor

#15720 fix(legend): add back symbolKeepAspect. optimize code logic.
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  test/runTest/server.js
Labels: PR: awaiting review, PR: author is committer, size/L

#15735 feat(type): provide ability to extend series option
  src/export/option.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#15761 chore: update download links in announcement email template
  build/source-release/template/announce-release.tpl
Labels: PR: awaiting review, PR: author is committer, size/XS

#15767 revert(line): revert the default design "make line bolder in the emphasis state"
  src/chart/line/LineSeries.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#15777 fix(aria): fix aria labels with dataset #15734
  src/visual/aria.ts
  test/aria-pie.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#15808 Fix a few typos (unkown -> unknown)
  .github/workflows/source-release.yml
  dist/echarts.js
  src/model/Model.ts
Labels: PR: awaiting review, PR: first-time contributor
