Repository apache/echarts, pull requests merged in 2021-01, with the labels that each got.

#13930 Fix/legend auto
  src/component/transform/filterTransform.ts
  src/component/transform/sortTransform.ts
  src/data/Source.ts
  src/data/helper/sourceHelper.ts
  src/data/helper/sourceManager.ts
  src/data/helper/transform.ts
  test/legend-feature.html
  test/ut/core/utHelper.ts
  test/ut/spec/component/dataZoom/helper.test.ts
  test/ut/spec/component/graphic/setOption.test.ts
  test/ut/spec/component/visualMap/setOption.test.ts
  test/ut/spec/data/dataTransform.test.ts
  test/ut/spec/model/Global.test.ts
  test/ut/spec/model/timelineMediaOptions.test.ts
  test/ut/spec/scale/interval.test.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13901 fix(heatmap): heatmap cannot be rendered in geo coordinate system with a large data.
  src/chart/heatmap/HeatmapView.ts
  test/heatmap-geo.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13933 fix: typo in comment
  extension-src/dataTool/prepareBoxplotData.ts
  src/chart/boxplot/prepareBoxplotData.ts
Labels: PR: awaiting review, size/XS

#13898 fix(bar-race): fix when no oldOrder
  src/chart/bar/BarView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13949 chore: rollup from lib in bundling. add ts check script
  .github/workflows/nodejs.yml
  .huskyrc
  README.md
  build/build.js
  build/config.js
  build/pre-publish.js
  build/progress.js
  build/release.js
  package.json
Labels: PR: author is committer, PR: awaiting review, size/XL

#13966 fix(Gauge): pointer.offsetCenter doesn't work without icon #13962
  src/chart/gauge/GaugeView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#13968 fix: gauge detail value animation broken by some previous commit.
  src/chart/gauge/GaugeView.ts
  src/chart/helper/labelHelper.ts
  src/chart/line/LineView.ts
  src/label/LabelManager.ts
  src/label/labelStyle.ts
  src/model/mixin/dataFormat.ts
  src/util/model.ts
  src/util/types.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13972 fix(loading): showLoading align center
  src/loading/default.ts
  test/loading.html
Labels: PR: author is committer, PR: awaiting review, size/M

#13848 Fix(tooltip.textStyle): fix color not working
  src/component/tooltip/TooltipModel.ts
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/tooltipMarkup.ts
  test/new-tooltip.html
Labels: PR: author is committer, PR: awaiting review, size/L

#13984 Fix unexpected global name usage
  .eslintrc-common.yaml
  src/.eslintrc.yaml
  src/core/echarts.ts
  src/core/locale.ts
  src/data/Source.ts
  src/model/globalDefault.ts
  src/util/format.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#13982 Provide Better APIs for extensions like ECharts GL, WordCloud, LiquidFill
  build/build.js
  build/pre-publish.js
  package.json
  src/component/timeline/SliderTimelineView.ts
  src/core/echarts.ts
  src/export/api.ts
  src/export/api/helper.ts
  src/extension.ts
  src/label/labelStyle.ts
  src/model/Component.ts
  src/scale/Scale.ts
  src/util/clazz.ts
  src/view/Chart.ts
  src/view/Component.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#13896 fix(endLabel): emphasis values
  src/chart/line/LineView.ts
  test/line-endLabel.html
Labels: PR: author is committer, PR: awaiting review, size/S

#13992 Fix(tooltip): 'findEventDispatcher' should add 'returnFirstMatch' f…
  src/component/tooltip/TooltipView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#13994 Fix: improvement and some fix of bar-race (realtimeSort)
  src/chart/bar/BarSeries.ts
  src/chart/bar/BarView.ts
  src/chart/helper/createListFromArray.ts
  src/chart/line/LineView.ts
  src/component/axis/AngleAxisView.ts
  src/component/axis/AxisBuilder.ts
  src/coord/Axis.ts
  src/coord/cartesian/Axis2D.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/cartesian/Grid.ts
  src/model/Global.ts
  src/scale/Ordinal.ts
  src/util/types.ts
  test/bar-race2.html
Labels: PR: author is committer, PR: awaiting review, size/XL

#13997 fix: when mouse on blank area tooltip throw error
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, size/XS

#14002 fix(toolbox): use current device pixel ratio by default for exporting crisp and clear images.
  src/component/toolbox/feature/SaveAsImage.ts
  src/core/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14003 doc: update repo name as TLP
  .asf.yaml
  README.md
Labels: PR: author is committer, PR: awaiting review, size/S

#14005 doc: update repo name as TLP
  .asf.yaml
  README.md
Labels: PR: author is committer, PR: awaiting review, size/S

#14006 fix(data): fix wrong data fetch when appendData with TypedArray
  src/data/helper/dataProvider.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14008 doc: remove incubating #14003
  DISCLAIMER
  NOTICE
  package.json
Labels: PR: author is committer, PR: awaiting review, size/S

#14010 fix: add back the default tooltip textStyle settings.
  src/component/tooltip/TooltipModel.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14054 test: migrate to ecSimpleTransition and ecSimpleOptionPlayer.
  test/custom-shape-morphing2.html
  test/custom-shape-morphing3.html
  test/data-transform-aggregate.html
  test/lib/config.js
  test/lib/ecSimpleOptionPlayer.js
  test/lib/ecSimpleTransform.js
  test/lib/myTransform/dist/myTransform.js
  test/lib/myTransform/dist/myTransform.js.map
  test/lib/myTransform/src/.eslintrc.yaml
  test/lib/myTransform/src/aggregate.ts
  test/lib/myTransform/src/id.ts
  test/lib/myTransform/src/index.ts
  test/lib/transitionPlayer.js
Labels: PR: author is committer, PR: awaiting review, size/M

#14073 fix(pie): deprecate series[pie].label.margin #14067
  src/chart/pie/PieSeries.ts
  tsconfig.json
Labels: PR: author is committer, PR: awaiting review, size/XS

#14087 Fix: add encodeHTML to avoid xss rishk
  CONTRIBUTING.md
  README.md
  package.json
  src/component/tooltip/tooltipMarkup.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#14108 fix(pie): pie chart avoidLabelOverlap hides label. close #13938
  src/chart/pie/labelLayout.ts
Labels: PR: awaiting review, size/S

#14056 Fix(handleIcon): icon without 'path://' will block
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14017 Fix(pie): labelLine is not hidden in some case
  src/chart/pie/PieSeries.ts
  src/chart/pie/PieView.ts
  test/pie-label.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14124 fix: add geo dependency in map. #14066
  src/chart/map/install.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14000 Fix: endLabel color support 'auto' 'inherit'
  src/chart/line/LineView.ts
  test/line-endLabel.html
Labels: PR: author is committer, PR: awaiting review, size/S
