Repository apache/echarts, pull requests merged in 2021-02, with the labels that each got.

#14164 test: add gauge regression test case
  test/gauge-case.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14175 fix: error thrown when `toolbox.feature.dataZoom: { show: false, yAxisIndex: false }`
  src/component/toolbox/feature/DataZoom.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14177 Feat: dev-fast use esbuild watch mode
  build/dev-fast.js
  package-lock.json
  package.json
Labels: PR: author is committer, PR: awaiting review, size/M

#14191 fix(showLoading): #14188 text of loading covered by charts
  src/loading/default.ts
  test/loading.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14267 Improve French translation
  src/i18n/langFR.ts
Labels: PR: awaiting review, size/M

#14263 Add LegendComponentOption.icon property type
  src/component/legend/LegendModel.ts
Labels: PR: awaiting review, size/XS

#14289 fix(type): exporting more necessary types for generating declarations in the extensions
  src/core/echarts.ts
  src/export/core.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14299 fix treemap display drill-down icon repeatedly.
  src/chart/treemap/TreemapView.ts
  test/treemap-action.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14314 fix(markLine): fix axis type in markLine data and close #14300
  src/component/marker/MarkLineModel.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14343 fix(markArea): markArea background color disappeared. close #13647
  src/component/marker/MarkAreaView.ts
Labels: PR: awaiting review, size/S

#14353 Export union members of option types separately
  src/export/option.ts
Labels: PR: awaiting review, size/S
