Repository apache/echarts, pull requests merged in 2021-04, with the labels that each got.

#14165 fix(gauge) #14131 Pointer can not display when icon is image
  src/chart/gauge/GaugeView.ts
  test/gauge-pointer.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14593 fix(line): ensure lineWidth is a number before addition in bolder logic
  src/chart/line/LineView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14574 Feat(effectScatter): add clip for effectScatter
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/effectScatter/EffectScatterView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14600 fix(graph): no edge symbol when offset is not defined
  src/chart/helper/Line.ts
Labels: PR: author is committer, PR: awaiting review

#14571 feature: support geoSVG
  src/chart/graph/GraphView.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/map/MapSeries.ts
  src/chart/map/mapSymbolLayout.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/treemap/TreemapView.ts
  src/component/geo/GeoView.ts
  src/component/geo/install.ts
  src/component/helper/MapDraw.ts
  src/component/tooltip/TooltipView.ts
  src/coord/View.ts
  src/coord/geo/Geo.ts
  src/coord/geo/GeoJSONResource.ts
  src/coord/geo/GeoModel.ts
  src/coord/geo/GeoSVGResource.ts
  src/coord/geo/Region.ts
  src/coord/geo/fix/diaoyuIsland.ts
  src/coord/geo/fix/geoCoord.ts
  src/coord/geo/fix/nanhai.ts
  src/coord/geo/fix/textCoord.ts
  src/coord/geo/geoCreator.ts
  src/coord/geo/geoJSONLoader.ts
  src/coord/geo/geoSVGLoader.ts
  src/coord/geo/geoSourceManager.ts
  src/coord/geo/geoTypes.ts
  src/coord/geo/mapDataStorage.ts
  src/coord/geo/parseGeoJson.ts
  src/core/echarts.ts
  src/data/OrdinalMeta.ts
  src/model/mixin/lineStyle.ts
  src/util/graphic.ts
  src/util/innerStore.ts
  src/util/states.ts
  src/util/types.ts
  src/view/Component.ts
  test/data/svg/Beef_cuts_France.svg
  test/data/svg/MacOdrum-LV5-floorplan-web.svg
  test/data/svg/Map_of_Iceland.svg
  test/data/svg/Sicily_prehellenic_topographic_map.svg
  test/data/svg/Veins_Medical_Diagram_clip_art.svg
  test/data/svg/flight-seats.svg
  test/data/svg/ksia-ext-plan-min.svg
  test/data/svg/seatmap-example.svg
  test/geo-layout.html
  test/geo-svg-demo.html
  test/geo-svg.html
  test/hoverFocus2.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/geo-svg-demo.json
  test/runTest/actions/geo-svg.json
  test/runTest/actions/hoverFocus2.json
  test/runTest/actions/tooltip-component.json
  test/tooltip-component.html
Labels: PR: author is committer, PR: awaiting review, size/XXL

#14578 fix(label): fix map label won't update its position when labelLayout is used
  src/component/helper/MapDraw.ts
  src/coord/geo/geoTypes.ts
  src/label/LabelManager.ts
  test/label-layout.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/label-layout.json
Labels: PR: author is committer, PR: awaiting review, size/M

#14243 fix(visualMap): use itemSymbol as default symbol type and fix #5719
  src/component/visualMap/PiecewiseModel.ts
  src/component/visualMap/VisualMapModel.ts
  src/component/visualMap/VisualMapView.ts
  test/visualMap-scatter-colorAndSymbol.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14542 fix(label): fix labels are not on the top bug.
  src/chart/line/LineView.ts
  src/chart/sankey/SankeyView.ts
  src/chart/treemap/Breadcrumb.ts
  src/chart/treemap/TreemapView.ts
  src/component/graphic/install.ts
  src/core/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#14608 style: remove unused imports. fix imports from entry
  src/component/graphic/install.ts
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  src/model/Series.ts
  test/runTest/client/index.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14609 fix(map): fix label layout may not update in map
  src/chart/map/MapView.ts
  src/component/helper/MapDraw.ts
  src/util/symbol.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#14624 Fix/geo location
  src/chart/map/MapView.ts
  src/component/helper/MapDraw.ts
  src/coord/View.ts
  src/coord/geo/GeoSVGResource.ts
  src/label/labelStyle.ts
  test/label-layout.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/label-layout.json
Labels: PR: author is committer, PR: awaiting review, size/M

#14630 fix(pie): fix pie display NaN labels
  src/chart/pie/PieView.ts
  test/pie-animation.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie-animation.json
Labels: PR: author is committer, PR: awaiting review, size/S

#14634 fix(bar): fix bar layout with borderWidth but no borderColor
  src/chart/bar/BarView.ts
  src/chart/line/LineSeries.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14638 fix: (1) fix treemap upperLabel opacity incorrect. (2) enhance TS type of `getVisual`.
  src/chart/helper/Symbol.ts
  src/chart/tree/TreeView.ts
  src/chart/treemap/TreemapView.ts
  src/data/Tree.ts
  src/util/symbol.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#14640 fix(sankey): make label in the front of rect, recover the change of #14417.
  src/chart/sankey/SankeyView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14693 fix(markLine): symbolOffset incorrectly marked as mandatory
  src/component/marker/MarkLineModel.ts
Labels: PR: author is committer, PR: awaiting review, PR: first-time contributor, size/XS

#14704 fix(map): ensure children have been added to group before calling `resetEventTriggerForRegion`.
  src/component/helper/MapDraw.ts
Labels: PR: awaiting review, priority: high, size/S

#14713 fix(tooltip): the position of tooltip may be incorrect if appendToBody.
  src/component/tooltip/TooltipHTMLContent.ts
  test/new-tooltip.html
Labels: PR: author is committer, PR: awaiting review, priority: high, size/M

#14702 fix(pie): hide labelLine emphasis when inside
  src/chart/pie/PieView.ts
  test/pie-label.html
Labels: PR: author is committer, PR: awaiting review, size/S

#14721 doc: update pr template with zr daily build
  .github/pull_request_template.md
Labels: PR: author is committer, PR: awaiting review, size/S

#14722 chore: enhance github workflow
  .github/workflows/nodejs.yml
  build/pre-publish.js
  package.json
  src/chart/helper/EffectSymbol.ts
  src/chart/pie/PieView.ts
  src/util/types.ts
  test/ut/core/setup.ts
  test/ut/index.d.ts
  test/ut/jest.config.js
  test/ut/tsconfig.json
Labels: PR: author is committer, PR: awaiting review, size/M

#14728 chore: workflow enhancement
  .github/workflows/ci.yml
  .github/workflows/source-release.yml
  build/.jshintrc
  build/source-release/prepareReleaseMaterials.js
  build/source-release/template/announce-release.tpl
  build/source-release/template/vote-release.tpl
  test/types/basic.ts
  test/types/event.ts
  test/types/importPartial.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#14742 chore: pack RELEASE_NOTE.txt into src.zip
  .github/workflows/source-release.yml
  build/source-release/prepareReleaseMaterials.js
Labels: PR: author is committer, PR: awaiting review, size/L

#14741 chore: comment error, adjust visualmap description
  src/echarts.all.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14743 test: add example for source release fast checking
  .github/workflows/source-release.yml
  test/check-build.html
  test/ie8.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14745 test: optimize size of visual regression test screenshot
  package.json
  test/runTest/blacklist.js
  test/runTest/cli.js
  test/runTest/client/index.html
  test/runTest/config.js
  test/runTest/genReport.js
  test/runTest/server.js
  test/runTest/store.js
  test/smooth.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14746 chore: fix typescript version
  package.json
Labels: PR: author is committer, PR: awaiting review, size/XS

#14747 Prepare to release 5.1.1
  .github/pull_request_template.md
  .github/workflows/ci.yml
  .github/workflows/nodejs.yml
  .github/workflows/source-release.yml
  build/.jshintrc
  build/pre-publish.js
  build/source-release/prepareReleaseMaterials.js
  build/source-release/template/announce-release.tpl
  build/source-release/template/vote-release.tpl
  package.json
  src/chart/helper/EffectSymbol.ts
  src/chart/pie/PieView.ts
  src/component/helper/MapDraw.ts
  src/component/marker/MarkLineModel.ts
  src/component/tooltip/TooltipHTMLContent.ts
  src/echarts.all.ts
  src/util/types.ts
  test/check-build.html
  test/ie8.html
  test/new-tooltip.html
  test/pie-label.html
  test/runTest/blacklist.js
  test/runTest/cli.js
  test/runTest/client/index.html
  test/runTest/config.js
  test/runTest/genReport.js
  test/runTest/server.js
  test/runTest/store.js
  test/smooth.html
  test/types/basic.ts
  test/types/event.ts
  test/types/importPartial.ts
  test/ut/core/setup.ts
  test/ut/index.d.ts
  test/ut/jest.config.js
  test/ut/tsconfig.json
Labels: PR: author is committer, PR: awaiting review, size/XL

#14758 feat(i18n): add Slovenian translation
  src/i18n/langSI.ts
Labels: PR: awaiting review, PR: first-time contributor, size/L

#14754 chore: add nightly build workflow
  .github/workflows/nightly.yml
  build/prepareNightly.js
Labels: PR: author is committer, PR: awaiting review, size/M

#14768 fix(geo): fix tooltip don't show on geo component.
  package-lock.json
  src/chart/map/MapView.ts
  src/coord/geo/GeoModel.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14772 chore: update package-lock.json
  package-lock.json
Labels: PR: author is committer, PR: awaiting review, size/XS

#13437 fix(toolbox): fix incorrect `currentType` in `magictypechanged` event.(#12359)
  src/component/toolbox/feature/MagicType.ts
  test/toolbox-stack-custom.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#14602 fix(linear-gradient): avoid the infinite value in `linearMap` util.
  src/chart/line/LineView.ts
  src/util/number.ts
  test/linear-gradient.html
Labels: PR: author is committer, PR: awaiting review, size/M

#14569 Fix(brush): clamp range when brush
  src/component/helper/BrushTargetManager.ts
  src/coord/CoordinateSystem.ts
  src/coord/cartesian/Cartesian2D.ts
  src/layout/barGrid.ts
  test/brush3.html
Labels: PR: author is committer, PR: awaiting review, size/M

#14806 Changed LineEndLabelOption.valueAnimation to be optional.
  src/chart/line/LineSeries.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14809 chore: remove unnecessary hidden files that may be published to npm
  .npmignore
Labels: PR: author is committer, PR: awaiting review, size/XS

#14823 chore: enable manual trigger nightly workflow
  .github/workflows/nightly.yml
Labels: PR: author is committer, PR: awaiting review, size/XS

#14825 chore: optimize style of README attention in nightly build
  build/prepareNightly.js
Labels: PR: author is committer, PR: awaiting review, size/XS
