Repository apache/echarts, pull requests merged in 2021-11, with the labels that each got.

#15998 fix(axis): only `value` has `scale` in cartesian
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  src/coord/axisModelCommonMixin.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/scaleRawExtentInfo.ts
  test/logScale.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16008 fix(type): ts error
  src/coord/axisModelCommonMixin.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#15990 feat(i18n): add Romanian translation
  src/i18n/langRO.ts
Labels: PR: awaiting review, size/L, PR: first-time contributor

#16001 fix: should show tooltip when all value are null
  src/chart/helper/createSeriesData.ts
Labels: PR: awaiting review, size/XS

#16070 [fix] dataZoom: optimize shadow render performance when roaming.
  src/component/axisPointer/BaseAxisPointer.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/dataZoom/roams.ts
  src/component/parallel/ParallelView.ts
  src/util/throttle.ts
Labels: PR: awaiting review, PR: author is committer, size/L

#16113 chore(core): remove `ssr` limit for `renderToSVGString`
  package-lock.json
  package.json
  src/core/echarts.ts
Labels: PR: awaiting review, PR: author is committer, size/S

#16128 Use github issue form for submitting issues.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: PR: awaiting review, PR: author is committer, size/L

#16129 fix typo in issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: PR: awaiting review, PR: author is committer, size/XS

#16130 chore: improve issue template description
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: PR: awaiting review, PR: author is committer, size/S

#16131 chore: tweak issue and pull request template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: PR: awaiting review, PR: author is committer, size/S

#16141 chore: update links in readme
  README.md
Labels: PR: awaiting review, PR: author is committer, size/S
