Repository apache/echarts, pull requests merged in 2021-03, with the labels that each got.

#14388 fix(dataZoom):fix dataZoom setting no effect
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14417 Fix(sankey): sankey label has higher z2
  src/chart/sankey/SankeyView.ts
  src/export/option.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#14413 fix(series): fix series data type judgment bug. close #14293
  src/model/Series.ts
  test/line-non-continuous.html
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14456 fix file names in license
  LICENSE
Labels: PR: author is committer, PR: awaiting review, size/XS

#14468 feat(i18n): added czech translation
  src/i18n/langCS.ts
Labels: PR: awaiting review, PR: first-time contributor, size/L

#14471 fix(tooltip): fix time axis formatter #14470
  src/util/format.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14473 feature: [tooltip] correct component tooltip cascade and support manually trigger component tooltip.
  src/component/axis/AxisBuilder.ts
  src/component/brush/BrushModel.ts
  src/component/graphic/install.ts
  src/component/legend/LegendView.ts
  src/component/toolbox/ToolboxModel.ts
  src/component/toolbox/ToolboxView.ts
  src/component/tooltip/TooltipView.ts
  src/util/graphic.ts
  src/util/innerStore.ts
  src/util/model.ts
  src/util/types.ts
  test/runTest/actions/__meta__.json
  test/tooltip-component.html
Labels: PR: author is committer, PR: awaiting review, size/L

#14246 perf(tooltip): improve the performance of tooltip.
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/helper.ts
Labels: PR: author is committer, PR: awaiting review, size/L

#14254 fix(custom): fix series label on custom series not working properly. close #14092
  src/util/styleCompat.ts
Labels: PR: awaiting review, size/XS

#14357 fix: remove legacy usage of transform
  src/chart/helper/EffectSymbol.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14375 fix(markLine): fix a bug that markLine `symbolOffset` doesn't work and some other issues.
  src/chart/helper/EffectSymbol.ts
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkLineView.ts
  src/data/List.ts
  src/util/types.ts
  src/visual/commonVisualTypes.ts
  src/visual/symbol.ts
  test/markLine-symbolRotate.html
  test/symbol3.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/L

#13638 fix(lines): discard extraneous data-points during lines animation
  src/chart/line/lineAnimationDiff.ts
  test/lines-extraneous.html
  test/runTest/actions/lines-extraneous.json
Labels: PR: awaiting review, size/S

#14552 test(line): add test case for line remove animation.
  test/line-extraneous.html
  test/lines-extraneous.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-extraneous.json
  test/runTest/actions/lines-extraneous.json
Labels: PR: author is committer, PR: awaiting review

#14553 feat(animation): add animaiton configuration in resize
  src/core/echarts.ts
  src/echarts.ts
  test/resize-animation.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/resize-animation.json
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/M

#13902 fix(Calendar): fix day label drifting. close #11508
  src/component/calendar/CalendarView.ts
Labels: PR: awaiting review, priority: high, size/XS
