Repository apache/echarts, pull requests merged in 2021-07, with the labels that each got.

#15271 fix: improve types in custom series and others.
  package-lock.json
  package.json
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/chart/custom/prepare.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/legend/LegendModel.ts
  src/component/toolbox/feature/Brush.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/DataZoom.ts
  src/component/toolbox/feature/MagicType.ts
  src/component/toolbox/feature/Restore.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/model/Global.ts
  src/model/Series.ts
  src/util/types.ts
  test/circle-packing-with-d3.html
  test/universalTransition.html
  test/universalTransition3.html
Labels: PR: author is committer, PR: awaiting review, size/L

#15243 fix(pie/sunburst): fix `borderRadius` can't be reset in pie series and sunburst series when setting it to `null` or `undefined`
  src/chart/helper/pieHelper.ts
  src/chart/pie/PieView.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/treemap/TreemapView.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#15207 fix: hightlight multiple series not work as expected
  src/core/echarts.ts
  test/hoverFocus.html
  test/hoverFocus2.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/hoverFocus.json
Labels: PR: awaiting review, size/M

#15283 fix(treemap): remove old nodes on disabled animation
  src/chart/treemap/TreemapView.ts
  test/treemap-setOption-twice-noAnimation.html
Labels: PR: author is committer, PR: awaiting review, priority: high, size/XS

#15286 fix(coord): fix coord dimension undefined for 3rd libs
  src/coord/geo/Geo.ts
  src/coord/geo/geoCreator.ts
  src/coord/polar/Polar.ts
  src/coord/polar/polarCreator.ts
  src/coord/single/Single.ts
  src/coord/single/singleCreator.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#15300 chore: test if stale bot works
  .github/stale.yml
Labels: PR: author is committer, PR: awaiting review, size/XS

#15303 more precise when determine if using id as key in universal transition
  src/animation/universalTransition.ts
  src/model/Series.ts
  test/runTest/actions/universalTransition2.json
  test/universalTransition2.html
Labels: PR: author is committer, PR: awaiting review, size/S

#15182 feat(label): sector label positions for polar bars and rotate for pies
  src/chart/bar/BarSeries.ts
  src/chart/bar/BarView.ts
  src/chart/pie/PieSeries.ts
  src/chart/pie/labelLayout.ts
  src/label/sectorLabel.ts
  test/bar-polar-label.html
  test/pie-label-rotate.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/L

#15297 fix(type): there is no function 'clampData' error in 'getMarkerPosition'
  src/chart/bar/BaseBarSeries.ts
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#14737 fix(marker): add missing type for symbolOffset, fix symbolOffset & symbolKeepAspect doesn't work in markPoint.
  src/chart/bar/PictorialBarView.ts
  src/chart/helper/EffectSymbol.ts
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/chart/radar/RadarView.ts
  src/component/axis/AxisBuilder.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkPointView.ts
  src/component/timeline/SliderTimelineView.ts
  src/coord/axisCommonTypes.ts
  src/util/symbol.ts
  src/util/types.ts
  src/visual/symbol.ts
Labels: PR: author is committer, PR: awaiting review, priority: high, size/L

#15308 chore: fix incorrect zrender modules import
  src/chart/bar/BarView.ts
  src/label/sectorLabel.ts
Labels: PR: author is committer, PR: awaiting review, size/S

#15281 fix(type): there is no polarIndex when coordinate of series is polar
  src/util/types.ts
Labels: PR: awaiting review, size/XS

#15309 fix(bar): set label to be inside when position is middle
  src/chart/bar/BarView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#15326 fix(gauge): guage detail label should be on top
  src/chart/gauge/GaugeView.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#15314 Fix(polar): polar would throw error if no label
  src/chart/bar/BarSeries.ts
  src/chart/bar/BarView.ts
Labels: PR: author is committer, PR: awaiting review, priority: high, size/XS

#15335 feat(effectScatter): make ripple effect count configurable
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/helper/EffectSymbol.ts
  src/chart/helper/SymbolDraw.ts
  test/effectScatter.html
Labels: PR: awaiting doc, PR: awaiting review, size/S

#15337 enable pointer's z-level adjustment in gauge chart & set default z-le…
  src/chart/gauge/GaugeSeries.ts
  src/chart/gauge/GaugeView.ts
Labels: PR: awaiting doc, PR: awaiting review, size/S

#14393 bug(tooltip): tooltip arrow will follow borderWidth. close #14373
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipView.ts
  test/scatter.html
Labels: PR: awaiting review, PR: first-time contributor, priority: high, size/M

#15313 fix(tooltip): tooltip should show DOM content instead of the string [object HTMLSpanElement]
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
  src/util/types.ts
  test/tooltip-domnode.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, priority: high, size/M

#14688 feat(gauge): Add data index and series index for indexing the data
  src/chart/gauge/GaugeView.ts
  src/data/List.ts
  src/util/innerStore.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#15363 fix(sankey): gradient should follow orient
  src/chart/sankey/SankeyView.ts
  test/sankey.html
Labels: PR: author is committer, PR: awaiting review

#15368 fix(candlestick): fix style lost after update
  src/chart/helper/whiskerBoxCommon.ts
  test/candlestick-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/candlestick-case.json
Labels: PR: author is committer, PR: awaiting review

#15361 fix(geo): fix geo switch from hidden to show fail.
  src/component/geo/GeoView.ts
  test/geo-update.html
  test/geoScatter.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/geo-update.json
Labels: PR: author is committer, PR: awaiting review

#15251 fix: root node related edge not removed when update data
  src/chart/tree/TreeView.ts
  test/tree-basic.html
Labels: PR: awaiting review, size/M

#15194 fix: hovered tooltip not update when options' series data changed
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, size/S

#14976 treemap: use treeAncestors in callback params
  src/chart/treemap/TreemapSeries.ts
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/S

#15381 fix(radar): lineStyle.join default round #13201
  src/chart/radar/RadarSeries.ts
  test/radar4.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review

#13788 feat(colorBy): provide option.colorBy #13731
  src/chart/funnel/FunnelSeries.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/lines/LinesSeries.ts
  src/chart/pie/PieSeries.ts
  src/chart/radar/RadarSeries.ts
  src/chart/sunburst/SunburstSeries.ts
  src/chart/sunburst/sunburstVisual.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/data/Tree.ts
  src/model/Series.ts
  src/model/globalDefault.ts
  src/util/types.ts
  src/visual/aria.ts
  src/visual/style.ts
  test/colorBy.html
  test/treemap-colorBy.html
Labels: PR: author is committer, PR: awaiting doc, PR: awaiting review, size/L

#15382 fix(colorBy): remove test case
  test/treemap-colorBy.html
Labels: PR: author is committer, PR: awaiting review

#15383 fix(candlestick): fix overflow data access in tooltip.
  src/component/tooltip/TooltipView.ts
  test/line-case.html
Labels: PR: author is committer, PR: awaiting review

#15396 fix(radar): fix radar symbol border is scaled
  src/chart/radar/RadarView.ts
  test/radar.html
Labels: PR: author is committer, PR: awaiting review

#15399 tooltip: fix probably null access
  src/component/tooltip/TooltipView.ts
Labels: PR: author is committer, PR: awaiting review

#15416 fix(line): normalize the infinite value when calculating the visual gradient.
  src/chart/line/LineView.ts
  test/linear-gradient.html
Labels: PR: author is committer, PR: awaiting review, size/S

#15417 reduce memory when chart instance is still hold after dispose
  src/core/echarts.ts
Labels: PR: author is committer, PR: awaiting review, size/M

#15410 Fix #13195 - Update way of parsing date
  src/util/number.ts
  test/ut/spec/util/number.test.ts
Labels: PR: awaiting review, size/XS

#15434 fix(xAxis): fix hour format at millisecond unit. close #15426
  src/util/time.ts
Labels: PR: awaiting review, size/XS
