Repository apache/echarts, pull requests merged in 2021-12, with the labels that each got.

#12793 fix(pictorialBar): Fixed a problem with rendering incorrectly when data is 0 and `borderWidth` is set to a non-0 value
  src/chart/bar/PictorialBarView.ts
  test/pictorial-zero-value-offset.html
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16193 doc: update badges in readme
  README.md
Labels: PR: awaiting review, PR: author is committer, size/XS

#16194 doc: fix link in readme
  README.md
Labels: PR: awaiting review, PR: author is committer, size/XS

#16196 chore: fix the link for the license badge and tweak the capitalization for several title labels.
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
Labels: PR: awaiting review, PR: author is committer, size/S

#16211 feat(i18n): add Italian translation
  src/i18n/langIT.ts
Labels: PR: awaiting review, size/L, PR: first-time contributor

#16213 chore(workflow): upgrade action version.
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
  .github/workflows/stale.yml
  src/i18n/langIT.ts
Labels: PR: awaiting review, PR: author is committer, size/S

#16212 fix(tooltip): fix tooltip lag issue when transition is disabled. (#16101)
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipView.ts
  test/tooltip-lag-glitch.html
Labels: PR: awaiting review, PR: author is committer, size/M

#16246 fix(bar): avoid creating subpaths in the sausage shape
  src/util/shape/sausage.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16250 Fix opacity wrong when using clone divideShape in universalTransition
  src/animation/universalTransition.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16034 fix(pie): label layout and text wrapping
  src/chart/pie/labelLayout.ts
  test/lib/testHelper.js
  test/pie-label-alignTo-adjust.html
  test/pie-label-alignTo.html
Labels: PR: awaiting review, PR: author is committer, size/L

#16229 fix(pie-label):#16208 When the total number of data is less than or equal to 2, the first data label shows a bug
  src/chart/pie/labelLayout.ts
  test/pie-label.html
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16210 fix: use common helper `createFloat32Array` to simplify the large array creation.
  src/chart/candlestick/candlestickLayout.ts
  src/layout/barGrid.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16225 introduce new keyframe based animation to graphic component and custom series
  package-lock.json
  package.json
  src/animation/basicTrasition.ts
  src/animation/customGraphicKeyframeAnimation.ts
  src/animation/customGraphicTransition.ts
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/chart/custom/prepare.ts
  src/chart/gauge/GaugeView.ts
  src/chart/helper/Symbol.ts
  src/component/graphic/GraphicModel.ts
  src/component/graphic/GraphicView.ts
  src/component/graphic/install.ts
  src/component/helper/MapDraw.ts
  src/data/helper/transform.ts
  src/export/option.ts
  src/util/layout.ts
  src/util/log.ts
  src/util/model.ts
  src/util/states.ts
  src/util/types.ts
  test/custom-animation.html
  test/custom-transition2.html
  test/graphic-animation-wave.html
  test/graphic-animation.html
  test/graphic-cases.html
  test/graphic-transition.html
  test/lib/testHelper.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/graphic-animation-wave.json
  test/runTest/actions/graphic-animation.json
  test/runTest/actions/graphic-transition.json
  test/ut/spec/component/graphic/setOption.test.ts
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/XXL

#16272 feat(ssr): add useViewBox opts in renderToSVGString
  src/core/echarts.ts
  test/ssr-animaiton-wave.html
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/XS

#16278 chore: add missing .js extension in export modules
  build/template/charts.js
  build/template/components.js
  build/template/core.js
  build/template/features.js
  build/template/renderers.js
Labels: PR: awaiting review, PR: author is committer, size/S

#16303 fix(state): fix default emphasis state of pattern.
  src/util/states.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16309 chore: reuse noop function from zrender util to reduce redundant code.
  src/chart/graph/install.ts
  src/chart/treemap/treemapAction.ts
  src/component/brush/install.ts
  src/component/helper/interactionMutex.ts
  src/component/tooltip/install.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16300 [Feature] [axis] add alignTicks for mutliple axis alignment.
  src/component/axis/CartesianAxisView.ts
  src/component/timeline/SliderTimelineView.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisHelper.ts
  src/coord/cartesian/Grid.ts
  src/coord/radar/Radar.ts
  src/scale/Interval.ts
  src/scale/Log.ts
  src/scale/Ordinal.ts
  src/scale/Scale.ts
  src/scale/Time.ts
  src/scale/helper.ts
  test/axis-align-ticks-random.html
  test/axis-align-ticks.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/axis-align-ticks.json
  test/ut/spec/scale/interval.test.ts
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/L

#16311 chore: update notice year to 2022.
  NOTICE
Labels: PR: awaiting review, PR: author is committer, size/XS
