Repository apache/echarts, pull requests merged in 2021-06, with the labels that each got.

#15072 fix(endLabel): endLabel should be displayed if show is true
  src/chart/line/LineSeries.ts
  src/chart/line/LineView.ts
  test/line-endLabel.html
Labels: PR: author is committer, PR: awaiting review, size/S

#15132 fix: pictorialBar display zero value error
  src/chart/bar/PictorialBarView.ts
  test/pictorial-zero-value.html
Labels: PR: awaiting review, size/XS

#15145 fix(pie): change the default borderJoin to `round`
  src/chart/pie/PieSeries.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#15144 fix(type): fix wrong type for PieSeries data and MapSeries data.
  src/chart/map/MapSeries.ts
  src/chart/pie/PieSeries.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#15141 fix(treemap): label.show=false will throw error
  src/chart/treemap/TreemapView.ts
  test/treemap-simple.html
Labels: PR: author is committer, PR: awaiting review, size/XS

#15088 fix(lines): fix lines can't be cleared by chart.clear()
  src/chart/line/LineView.ts
  src/chart/lines/LinesView.ts
  test/lines-bus.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/lines-bus.json
Labels: PR: author is committer, PR: awaiting review, priority: high, size/XS

#15199 fix(sankey): fix dragger bug for sankey when series data key name is nodes
  src/chart/sankey/SankeySeries.ts
  test/sankey-series-nodes.html
Labels: PR: awaiting review, PR: first-time contributor, size/XS

#15172 feat:emphasis color inherit support
  src/component/tooltip/TooltipView.ts
  src/util/states.ts
  test/emphasis-inherit.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/emphasis-inherit.json
Labels: PR: awaiting review, PR: first-time contributor, size/S

#15218 fix: error message typo
  src/data/helper/dataProvider.ts
Labels: PR: awaiting review, size/XS

#15244 fix(tooltip): fix a typo `pointer-event` -> `pointer-events`.
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, PR: awaiting review, size/XS

#14620 fix(timeline): trigger timelineplaychange event when play to the end
  src/component/timeline/timelineAction.ts
  test/timeline-event.html
Labels: PR: author is committer, PR: awaiting review, size/S

#15263 fix(dts): Wrong type for svg handling in .d.ts. close #15262
  src/coord/geo/geoTypes.ts
Labels: PR: awaiting review, size/XS
