Repository apache/echarts, pull requests merged in 2022-02, with the labels that each got.

#16463 fix(tooltip): set legend.tooltip.enterable along with tooltip.enterable. close #16440
  src/component/tooltip/TooltipView.ts
  test/tooltip-setOption.html
Labels: PR: awaiting review, size/XS

#16469 fix(pictorialBar): set valueLineWidth NaN value to zero. close #16423
  src/chart/bar/PictorialBarView.ts
Labels: PR: awaiting review, size/XS

#16493 [Feature] add borderRadius option to heatmap
  src/chart/bar/BarSeries.ts
  src/chart/funnel/FunnelSeries.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/heatmap/HeatmapSeries.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/lines/LinesSeries.ts
  src/chart/parallel/ParallelSeries.ts
  src/chart/radar/RadarSeries.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/util/types.ts
  test/heatmap-borderRadius.html
Labels: PR: awaiting review, size/M, PR: first-time contributor

#16321 fix(dataview): hide tooltip when data view is open.
  src/component/toolbox/feature/DataView.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16509 Merge `next` branch into `master` branch.
  src/component/toolbox/feature/DataView.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16513 fix(graphic): fix `cursor` doesn't work in `graphic` component.
  src/component/graphic/GraphicView.ts
  test/graphic-cases.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16525 perf(lines): fix potential memory leak in the effect line when setOption with notMerge
  src/chart/helper/EffectLine.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/tree/TreeView.ts
  test/lib/testHelper.js
  test/node/ssr.js
Labels: PR: awaiting review, PR: author is committer, size/M

#16431 fix(line): using sampling with lttb, NaN point should not be filtered.
  src/data/DataStore.ts
  test/line-sampling.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-sampling.json
Labels: PR: revision needed, size/S

#16435 fix(line): 过滤空节点, 避免阶梯线条变为斜线
  src/chart/line/LineView.ts
  test/line-step.html
Labels: PR: awaiting review, size/M, PR: first-time contributor

#16425 fix(sunburst) set the position of label in center when angle is 2π. c…
  src/chart/sunburst/SunburstPiece.ts
  test/sunburst-label.html
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16582 feat(i18n): add korean translation
  src/i18n/langKO.ts
Labels: PR: awaiting review, size/L

#16187 feat(event): provide label index in axis events
  src/component/axis/AxisBuilder.ts
  test/axisLabel.html
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/XS

#15428 feat(graph): simple graph draggable. close #14510
  src/chart/graph/GraphView.ts
  src/chart/graph/circularLayoutHelper.ts
  src/component/helper/RoamController.ts
  test/graph-draggable.html
Labels: PR: revision needed, size/L, PR: first-time contributor

#16589 Merge master into release for 5.3.1
  src/chart/bar/BarSeries.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/funnel/FunnelSeries.ts
  src/chart/gauge/GaugeSeries.ts
  src/chart/heatmap/HeatmapSeries.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/EffectLine.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/line/LineView.ts
  src/chart/lines/LinesSeries.ts
  src/chart/parallel/ParallelSeries.ts
  src/chart/pie/PieView.ts
  src/chart/radar/RadarSeries.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/tree/TreeView.ts
  src/component/axis/AxisBuilder.ts
  src/component/graphic/GraphicView.ts
  src/component/toolbox/feature/DataView.ts
  src/component/tooltip/TooltipView.ts
  src/data/DataStore.ts
  src/i18n/langKO.ts
  src/processor/dataSample.ts
  src/util/format.ts
  src/util/types.ts
  test/axisLabel.html
  test/graphic-cases.html
  test/heatmap-borderRadius.html
  test/lib/testHelper.js
  test/line-sampling.html
  test/line-step.html
  test/node/ssr.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-sampling.json
  test/sunburst-label.html
  test/tooltip-setOption.html
Labels: PR: awaiting review, PR: author is committer, size/XXL
