Repository apache/echarts, pull requests merged in 2022-09, with the labels that each got.

#17582 fix: ensure compatibility with typescript@4.8
  src/animation/basicTransition.ts
  src/chart/bar/BaseBarSeries.ts
  theme/macarons.js
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#15291 Export type elementevent
  src/export/core.ts
Labels: size/XS

#17614 Add #15291 #17598 #17587 #17551 to release for 5.4.0
  src/chart/sunburst/sunburstAction.ts
  src/export/core.ts
  src/util/log.ts
Labels: PR: author is committer, size/XS

#17616 chore(stale): issues with milestone should not be marked as stale
  .github/workflows/stale.yml
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17647 fix(timeline): fix chart can't work when axis line is not shown
  src/component/timeline/SliderTimelineView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/timeline-case.json
  test/timeline-case.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#17510 fix: legend inverse doesn't work if series/data have the same name
  src/component/legend/LegendModel.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor, PR: doc unchanged

#17606 chore(lint): enforce consistent spacing after comment starts
  .eslintrc-common.yaml
  src/coord/axisHelper.ts
  src/core/task.ts
  src/export/api.ts
  src/layout/barPolar.ts
  src/util/states.ts
  src/util/types.ts
Labels: PR: author is committer, size/S

#17098 fix: markArea of bar series now covers whole categories specified
  src/chart/bar/BaseBarSeries.ts
  src/component/marker/MarkAreaView.ts
  src/coord/CoordinateSystem.ts
  src/model/Series.ts
  test/bar-markArea.html
Labels: size/M

#17695 style(lint): fix spacing issues and remove unused imports and functions
  .github/workflows/ci.yml
  .huskyrc
  src/chart/bar/BaseBarSeries.ts
  src/chart/boxplot/boxplotVisual.ts
  src/chart/boxplot/install.ts
  src/chart/graph/GraphView.ts
  src/chart/line/helper.ts
  src/chart/map/MapSeries.ts
  src/chart/sankey/sankeyLayout.ts
  src/chart/sunburst/sunburstLayout.ts
  src/chart/tree/TreeSeries.ts
  src/chart/treemap/TreemapSeries.ts
  src/component/dataZoom/DataZoomModel.ts
  src/component/legend/LegendView.ts
  src/component/marker/MarkAreaView.ts
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkPointModel.ts
  src/component/marker/markerHelper.ts
  src/coord/cartesian/Grid.ts
  src/coord/geo/GeoModel.ts
  src/coord/geo/GeoSVGResource.ts
  src/coord/geo/fix/textCoord.ts
Labels: PR: author is committer, size/M

#17694 docs(extension/bmap): improve documentation of bmap extension
  extension-src/bmap/BMapModel.ts
  extension-src/bmap/README.md
Labels: PR: author is committer, size/M, PR: doc ready

#17691 fix #17633: add gauge sectors in the order of the "clockwise" option
  src/chart/gauge/GaugeView.ts
  test/gauge-case.html
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#17715 fix(pie): fix `labelLine` NPE when `minShowLabelRadian` is set
  src/chart/pie/labelLayout.ts
  test/pie-label.html
Labels: PR: author is committer, size/XS, PR: doc unchanged
