Repository apache/echarts, pull requests merged in 2022-12, with the labels that each got.

#17997 fix(polar): polar bar animation should start from r0 rather than 0
  src/chart/bar/BarView.ts
  src/chart/sunburst/SunburstPiece.ts
  test/bar-polar-animation.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/bar-polar-animation.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18002 chore: update version in package-lock
  package-lock.json
Labels: PR: author is committer, size/XS

#18055 chore(deps-dev): bump terser from 5.3.8 to 5.16.1
  package-lock.json
  package.json
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18061 chore: fix several typos
  src/component/axisPointer/BaseAxisPointer.ts
  src/component/axisPointer/axisTrigger.ts
  src/component/axisPointer/modelHelper.ts
  src/component/axisPointer/viewHelper.ts
  src/component/dataZoom/SliderZoomView.ts
  src/component/helper/BrushController.ts
  src/component/helper/BrushTargetManager.ts
  src/component/helper/MapDraw.ts
  src/component/toolbox/ToolboxView.ts
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/seriesFormatTooltip.ts
  src/component/tooltip/tooltipMarkup.ts
  src/component/visualMap/ContinuousModel.ts
  src/component/visualMap/ContinuousView.ts
  src/component/visualMap/PiecewiseModel.ts
  src/component/visualMap/VisualMapModel.ts
Labels: size/M, PR: doc unchanged

#18070 fix(tree): change symbol type. close #17946
  src/chart/tree/TreeSeries.ts
Labels: size/XS, PR: doc unchanged

#18032 fix(ssr): fix label doesn't show in line series when `ssr` is enabled
  src/chart/line/LineView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/svg-ssr.json
  test/svg-ssr.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#18103 chore: fix a few typos
  src/component/axis/AxisBuilder.ts
  src/component/transform/filterTransform.ts
  src/model/Series.ts
Labels: size/S, PR: doc unchanged

#18115 fix: update example
  test/gauge-distance.html
  test/gauge-group-title-detail.html
  test/gauge-simple.html
  test/gauge.html
  test/graph-grid.html
Labels: size/XS

#18128 chore: update notice year to 2023
  NOTICE
Labels: PR: author is committer, size/XS
