Repository apache/echarts, pull requests merged in 2022-07, with the labels that each got.

#17304 chore(workflow): close stale issues as not planned rather than completed
  .github/workflows/stale.yml
Labels: PR: author is committer, size/XS

#17308 fix(custom): fix custom elements probably can't be removed due to NPE when applying leave transition
  src/chart/custom/CustomView.ts
  test/custom.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/custom.json
Labels: PR: author is committer, size/S, PR: doc unchanged

#17317 chore(workflow): upgrade stale action to v5
  .github/workflows/stale.yml
Labels: PR: author is committer, size/XS

#17329 fix(axis): fix axis symbol is not reversed when axis is reversed
  src/component/axis/AxisBuilder.ts
  test/axis-arrow.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17346 fix(visualMap): fix the indicator doesn't show when hovering on map label
  src/component/helper/MapDraw.ts
  src/component/visualMap/ContinuousView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/geo-map.json
Labels: PR: author is committer, size/S, PR: doc unchanged

#17390 fix(type): add missing type `number` to `emphasis.scale` for scatter/line/graph series
  src/action/roamHelper.ts
  src/chart/graph/GraphSeries.ts
  src/chart/graph/install.ts
  src/chart/line/LineSeries.ts
  src/chart/scatter/ScatterSeries.ts
  src/chart/tree/treeAction.ts
  src/component/geo/install.ts
Labels: PR: author is committer, size/M, PR: doc unchanged

#17406 fix(svg): encode HTML special characters when generating SVG string
  package-lock.json
  package.json
  src/util/format.ts
Labels: PR: author is committer, size/S, PR: doc unchanged

#17411 fix(axis): fix `inverse` option does not work for `singleAxis`
  src/coord/single/Single.ts
  src/coord/single/SingleAxis.ts
Labels: size/XS, PR: doc unchanged

#17383 style: spelling mistakes
  src/component/marker/MarkAreaView.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkPointView.ts
  src/component/marker/markerHelper.ts
Labels: size/S, PR: first-time contributor

#17412 fix(pie): fix `labelLine` may not be hidden when `minShowLabelRadian` is specified
  src/chart/pie/labelLayout.ts
  test/pie-label.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie-label.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17349 fix(custom): fix elements may not be removed after updates #17333
  src/chart/custom/CustomView.ts
  test/custom-update.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/custom-update.json
Labels: PR: author is committer, size/M, PR: doc ready

#17442 fix(symbol): fix `emphasis.scale` can't be reset and specified values may not be respected
  src/chart/helper/Symbol.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/symbol.json
  test/runTest/runtime/ActionPlayback.js
  test/symbol.html
Labels: PR: author is committer, size/S, PR: doc unchanged
