Repository apache/echarts, pull requests merged in 2022-05, with the labels that each got.

#16904 feat(View): `View` center supports `string`
  src/action/roamHelper.ts
  src/chart/graph/createView.ts
  src/chart/graph/install.ts
  src/chart/tree/TreeView.ts
  src/chart/tree/treeAction.ts
  src/component/geo/install.ts
  src/coord/View.ts
  src/coord/geo/geoCreator.ts
  src/util/types.ts
  test/graph-simple.html
  test/tree-legend.html
Labels: PR: awaiting review, PR: author is committer, size/M

#16972 feat(piecewise): `selecedtMode` support `boolean`
  src/component/visualMap/PiecewiseModel.ts
  src/component/visualMap/PiecewiseView.ts
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/XS

#17009 feat(tree): `tree` focus supports `relative`
  src/chart/tree/TreeSeries.ts
  src/chart/tree/TreeView.ts
  test/tree-legend.html
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/S

#17007 fix(graphic): fix some options may be unexpectedly reset on update
  src/component/graphic/GraphicModel.ts
  src/component/graphic/GraphicView.ts
  test/graphic-cases.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/graphic-cases.json
Labels: PR: awaiting review, PR: author is committer, size/M

#17073 fix(time): Quarters split the year into 4 quarters not 3. close #17057
  src/util/time.ts
Labels: PR: awaiting review, size/XS

#16850 Fix prepareCustoms key for Single axis.
  src/chart/bar/PictorialBarView.ts
  src/chart/custom/CustomView.ts
  test/custom.html
Labels: PR: awaiting review, size/S, PR: first-time contributor

#17094 docs: remove a broken link and update info in CONTRIBUTING.md.
  CONTRIBUTING.md
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#17086 feat: add new stacking strategies
  src/processor/dataStack.ts
  src/util/types.ts
  test/area-stack.html
Labels: PR: awaiting review, PR: author is committer, size/S
