Repository apache/echarts, pull requests merged in 2022-08, with the labels that each got.

#17450 fix(custom): set ignore only if old child exists
  src/chart/custom/CustomView.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17452 chore: fix wrong imports from `echarts.all`
  src/animation/customGraphicKeyframeAnimation.ts
  src/chart/custom/CustomView.ts
  src/coord/geo/geoCreator.ts
Labels: PR: author is committer, size/S

#17275 perf(pie): optimize performance of pie series
  src/chart/pie/PieSeries.ts
  src/util/number.ts
  test/pie-percent.html
  test/pie3.html
Labels: size/M, PR: first-time contributor, PR: doc unchanged

#17482 fix(theme): fix the abandoned normal level in the theme file
  theme/infographic.js
  theme/macarons.js
  theme/macarons2.js
  theme/shine.js
  theme/tech-blue.js
  theme/tool/option/area.js
  theme/tool/option/bar.js
  theme/tool/option/graph.js
  theme/tool/option/map.js
  theme/tool/option/pie.js
Labels: size/XL, PR: first-time contributor, PR: doc unchanged

#16985 feat(gauge): axisLabel support angle rotating. close 15944
  src/chart/gauge/GaugeSeries.ts
  src/chart/gauge/GaugeView.ts
  test/gauge-case.html
  test/gauge-simple.html
Labels: size/M

#17237 fix: sliderZoom in candlestick dataset error
  src/component/dataZoom/SliderZoomView.ts
Labels: size/XS, PR: doc unchanged

#17322 fix(log): fix log axis breaks a single data whose log value is negative
  src/scale/Interval.ts
  src/scale/Log.ts
  test/logScale.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#17132 feat(pie): support specifying coordinate system for pie series.
  extension-src/bmap/BMapCoordSys.ts
  src/chart/pie/pieLayout.ts
  test/pie-coordinate-system.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#17426 feat(bar-race): provide subPixelOptimize option to solve #14679
  src/component/axis/AxisBuilder.ts
  src/component/axis/CartesianAxisView.ts
  src/component/axis/SingleAxisView.ts
  src/util/graphic.ts
  test/bar-race.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#17102 Feature: coarse pointer tolerance
  package-lock.json
  package.json
  src/chart/bar/BarView.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/helper/LargeLineDraw.ts
  src/chart/helper/LargeSymbolDraw.ts
  src/core/echarts.ts
  test/coarse-pointer.html
  test/lib/caseFrame.js
  test/lib/config.js
  test/lib/testHelper.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/coarse-pointer.json
  test/runTest/cli.js
  test/runTest/client/client.css
  test/runTest/client/client.js
  test/runTest/client/index.html
  test/runTest/server.js
  test/runTest/store.js
Labels: PR: author is committer, PR: awaiting doc, size/S

#17538 Master next to master for v5.4
  package-lock.json
  package.json
  src/chart/bar/BarView.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/graph/GraphView.ts
  src/chart/graph/circularLayoutHelper.ts
  src/chart/helper/EffectLine.ts
  src/chart/helper/EffectPolyline.ts
  src/chart/helper/LargeLineDraw.ts
  src/chart/helper/LargeSymbolDraw.ts
  src/chart/helper/LineDraw.ts
  src/component/helper/RoamController.ts
  src/core/echarts.ts
  src/util/format.ts
  test/coarse-pointer.html
  test/graph-draggable.html
  test/lib/caseFrame.js
  test/lib/config.js
  test/lib/testHelper.js
  test/runTest/actions/__meta__.json
  test/runTest/actions/coarse-pointer.json
  test/runTest/cli.js
  test/runTest/client/client.css
  test/runTest/client/client.js
  test/runTest/client/index.html
  test/runTest/server.js
  test/runTest/store.js
Labels: PR: author is committer, size/L

#17551 fix(theme): fix tooltips text style of the theme macarons
  theme/macarons.js
Labels: size/XS, PR: doc unchanged

#17587 fix the wrong code of `deprecateReplaceLog` in sunburstAction.ts
  src/chart/sunburst/sunburstAction.ts
Labels: size/XS, PR: doc unchanged

#17598 fix a typo error in `log.ts`
  src/util/log.ts
Labels: size/XS, PR: first-time contributor
