Repository apache/echarts, pull requests merged in 2022-04, with the labels that each got.

#16820 chore: update release materials, KEYS, README
  KEYS
  README.md
  build/source-release/template/vote-release.tpl
  package.json
Labels: PR: awaiting review, PR: author is committer, size/L

#16824 fix(DataStore): fix typo 'Invalid'. close #16786
  src/data/DataStore.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16836 ci: add lint step
  .github/workflows/ci.yml
Labels: PR: awaiting review, PR: author is committer, size/XS

#16857 [infra] reset notifications to commits@echarts for commits, PRs and issues
  .asf.yaml
Labels: PR: awaiting review, PR: author is committer, size/XS, PR: first-time contributor

#16854 fix: bug 16849
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: awaiting review, size/XS

#16867 fix(graph): user cursor has higher priority
  src/chart/graph/GraphSeries.ts
  src/chart/graph/GraphView.ts
  src/chart/helper/Symbol.ts
  test/graph-symbol.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16881 ci: fix node modules cache doesn't work
  .github/workflows/ci.yml
Labels: PR: awaiting review, PR: author is committer, size/S

#16861 fix: markArea display filter correction
  src/component/marker/MarkAreaView.ts
  src/component/marker/markerHelper.ts
  src/coord/cartesian/Cartesian2D.ts
  test/markArea.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/markArea.json
Labels: PR: awaiting review, size/M

#16897 fix(types): graph autoCurveness option
  src/chart/graph/GraphSeries.ts
Labels: PR: awaiting review, size/XS

#16922 fix: legend visual still with decal when user set 'legend.itemStyle.decal' to 'none'
  src/component/legend/LegendView.ts
Labels: PR: awaiting review, size/M

#16945 Merge master to next
  src/component/legend/LegendView.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16943 feat(LineDraw):series-lines support the effect animation go back
  src/chart/helper/EffectLine.ts
  src/chart/helper/EffectPolyline.ts
  src/chart/helper/LineDraw.ts
Labels: PR: awaiting review, size/M, PR: first-time contributor

#16939 fix: tooltip content changes with axis extent when 'triggerOn' set to 'click'
  src/component/tooltip/TooltipView.ts
Labels: PR: awaiting review, size/XS

#16950 fix(tree): radial tree with single root doesn't work
  src/chart/tree/TreeView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tree-radial.json
  test/tree-radial.html
Labels: PR: awaiting review, size/XS

#16966 chore: fix broken external editor links
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: PR: awaiting review, PR: author is committer, size/XS
