Repository apache/echarts, pull requests merged in 2022-11, with the labels that each got.

#17857 chore(nightly-build): fix potential npm publish error due to time conflict
  .github/workflows/nightly-next.yml
Labels: PR: author is committer, size/XS

#17873 chore: fix various typos
  src/coord/Axis.ts
  src/coord/CoordinateSystem.ts
  src/coord/View.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  src/coord/axisHelper.ts
  src/coord/axisTickLabelBuilder.ts
  src/coord/cartesian/defaultAxisExtentFromData.ts
  src/coord/geo/Geo.ts
  src/coord/geo/GeoModel.ts
  src/coord/geo/GeoSVGResource.ts
  src/coord/geo/geoTypes.ts
  src/coord/parallel/Parallel.ts
  src/coord/parallel/ParallelModel.ts
  src/coord/scaleRawExtentInfo.ts
  src/layout/barGrid.ts
  src/util/graphic.ts
  src/util/symbol.ts
  src/util/types.ts
  src/visual/style.ts
Labels: size/M, PR: doc unchanged

#17861 fix(data): change deprecated `map.data.hasOwnProperty` to `map.hasKey`
  package-lock.json
  package.json
  src/data/helper/createDimensions.ts
Labels: PR: author is committer, size/S, PR: doc unchanged

#17875 fix(tooltip): fix tooltip arrow may cover the content when border is wide
  src/component/tooltip/TooltipHTMLContent.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-domnode.json
  test/tooltip-domnode.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17876 fix(heatmap): fix heatmap label may overlap when `dataZoom` is enabled
  src/chart/heatmap/HeatmapView.ts
  test/heatmap.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/heatmap.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17882 chore: start a local server for testing when run dev #17868
  README.md
  package.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17887 style: fix code style flaw and remove unnecessary default parameter.
  src/chart/bar/BaseBarSeries.ts
  src/component/marker/MarkAreaView.ts
  src/model/Series.ts
  test/bar-markArea.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#17892 feat(type): export `ECElementEvent` for TypeScript
  src/export/core.ts
Labels: typescript, size/XS, PR: first-time contributor, PR: doc unchanged

#17896 chore: fix some typos
  src/data/Source.ts
  src/label/labelGuideHelper.ts
  src/label/labelStyle.ts
  src/util/ECEventProcessor.ts
  src/util/KDTree.ts
  src/util/clazz.ts
  src/util/conditionalExpression.ts
  src/util/decal.ts
  src/util/format.ts
  src/util/graphic.ts
  src/util/layout.ts
  src/util/model.ts
  src/util/number.ts
  src/util/states.ts
  src/util/styleCompat.ts
  src/util/types.ts
Labels: size/L, PR: doc unchanged

#17904 chore: fix various typos
  src/chart/bar/BarView.ts
  src/chart/bar/BaseBarSeries.ts
  src/chart/bar/install.ts
  src/chart/bar/installPictorialBar.ts
  src/chart/map/MapView.ts
  src/data/DataStore.ts
  src/data/Source.ts
  src/data/helper/createDimensions.ts
  src/data/helper/dataProvider.ts
  src/data/helper/dataStackHelper.ts
  src/data/helper/dataValueHelper.ts
  src/data/helper/dimensionHelper.ts
  src/data/helper/sourceHelper.ts
  src/data/helper/sourceManager.ts
  src/data/helper/transform.ts
Labels: size/M, PR: doc unchanged

#17217 fix(marker): fix `markArea` doesn't show when using `x/y` pixel but `coord` is not defined
  src/component/marker/MarkAreaView.ts
  src/component/marker/markerHelper.ts
  test/markArea.html
Labels: size/M, PR: doc unchanged

#17780 fix(lines): add missing `function` callback into `lineStyle.color` for lines series.
  src/chart/lines/LinesSeries.ts
  src/chart/lines/LinesView.ts
Labels: PR: author is committer, size/S, PR: doc unchanged

#17906 feat(type): export `GraphicComponentTextOption`
  src/component/graphic/GraphicModel.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#17913 chore: fix a few typos
  src/chart/custom/CustomView.ts
  src/chart/graph/forceHelper.ts
  src/chart/line/LineView.ts
  src/chart/map/MapSeries.ts
  src/chart/pie/labelLayout.ts
  src/chart/sunburst/SunburstSeries.ts
  src/chart/themeRiver/ThemeRiverSeries.ts
  src/chart/tree/layoutHelper.ts
  src/chart/treemap/TreemapSeries.ts
  src/chart/treemap/TreemapView.ts
  src/chart/treemap/treemapLayout.ts
  src/chart/treemap/treemapVisual.ts
  src/component/dataZoom/AxisProxy.ts
  src/component/dataZoom/DataZoomModel.ts
  src/component/graphic/GraphicModel.ts
  src/component/graphic/install.ts
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  src/component/parallel/ParallelView.ts
Labels: size/L, PR: doc unchanged

#17917 fix(type): add `string` & `number` type into the `center` option of pie series
  src/chart/pie/PieSeries.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17920 fix(pie): fix `center` may not be converted to correct point when coordinate system is specified
  src/chart/pie/pieLayout.ts
  test/pie-coordinate-system.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17934 fix(dataZoom): fallback to extent start/end when parsed value or percent is invalid.
  src/component/dataZoom/AxisProxy.ts
  test/axis-lastLabel.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17944 fix(stack): revert pr #17809
  src/processor/dataStack.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17978 feat(i18n): add Hungarian(hu_HU) translation
  package-lock.json
  src/i18n/langHU.ts
Labels: size/L, PR: doc unchanged

#17979 fix(core): use `!=` to check if series is excluded as native map returns `undefined` rather than `null`
  src/core/echarts.ts
Labels: PR: author is committer, size/M, PR: doc unchanged

#17984 chore: update `zrender`
  package-lock.json
  package.json
Labels: PR: author is committer, size/XS
