Repository apache/echarts, pull requests merged in 2022-01, with the labels that each got.

#16184 fix(lines): fix NPE issue when lines series has no coordinate system.
  src/chart/helper/LineDraw.ts
  src/chart/lines/linesLayout.ts
  test/lines-graph.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16318 using utility methods for value type checking
  src/animation/basicTrasition.ts
  src/chart/funnel/funnelLayout.ts
  src/chart/gauge/GaugeView.ts
  src/chart/graph/categoryFilter.ts
  src/chart/graph/categoryVisual.ts
  src/chart/helper/EffectLine.ts
  src/chart/helper/createClipPathFromCoordSys.ts
  src/chart/helper/multipleGraphEdgeHelper.ts
  src/chart/helper/treeHelper.ts
  src/chart/line/LineView.ts
  src/chart/lines/LinesSeries.ts
  src/chart/pie/labelLayout.ts
  src/chart/sankey/SankeyView.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/sunburst/sunburstLayout.ts
  src/chart/sunburst/sunburstVisual.ts
  src/component/axis/AxisBuilder.ts
  src/component/calendar/CalendarView.ts
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  src/component/marker/MarkAreaView.ts
  src/component/marker/MarkLineView.ts
  src/component/toolbox/ToolboxView.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/component/tooltip/TooltipRichContent.ts
  src/coord/axisAlignTicks.ts
  src/coord/axisHelper.ts
  src/coord/cartesian/Grid.ts
  src/coord/geo/Geo.ts
  src/coord/geo/GeoModel.ts
  src/coord/radar/Radar.ts
  src/coord/radar/RadarModel.ts
  src/core/echarts.ts
  src/data/Graph.ts
  src/data/OrdinalMeta.ts
  src/data/SeriesData.ts
  src/data/Tree.ts
  src/data/helper/dataValueHelper.ts
  src/data/helper/transform.ts
  src/label/LabelManager.ts
  src/label/sectorLabel.ts
  src/model/Model.ts
  src/model/mixin/dataFormat.ts
  src/processor/dataSample.ts
  src/processor/negativeDataFilter.ts
  src/scale/Ordinal.ts
  src/scale/Time.ts
  src/scale/helper.ts
  src/util/clazz.ts
  src/util/conditionalExpression.ts
  src/util/decal.ts
  src/util/model.ts
  src/util/number.ts
  src/util/time.ts
  src/visual/VisualMapping.ts
  src/visual/aria.ts
  src/visual/style.ts
Labels: PR: awaiting review, PR: author is committer, size/XL

#16322 fix(map): some labels won't be shown when legend is enabled and no label formatter specified.
  src/chart/map/MapView.ts
  test/map-china.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16243 Support using dataType param to specify edge highlighting
  src/util/states.ts
  src/view/Chart.ts
  test/graph-edge-highlight.html
Labels: PR: awaiting review, PR: awaiting doc, size/S, PR: first-time contributor

#16329 fix(polar): fix edge symbols are clipped unexpectedly for the tiny offset.
  src/coord/polar/Polar.ts
  test/clip.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16307 fix(pie): tangential rotation with startAngle #15980
  src/chart/pie/labelLayout.ts
  test/pie-label-rotate.html
Labels: PR: awaiting review, PR: author is committer, size/M

#16332 add valueFormatter in tooltip
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/tooltipMarkup.ts
  src/model/mixin/dataFormat.ts
  src/util/types.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-valueFormatter.json
  test/tooltip-valueFormatter.html
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/L

#16203 fix(axis): axis label width when overflow is set
  src/chart/treemap/TreemapSeries.ts
  src/model/mixin/textStyle.ts
  test/bar3.html
Labels: PR: awaiting review, PR: author is committer, size/M

#16339 fix(line): fix endLabel have error when series is filtered.
  src/chart/line/LineView.ts
  test/line-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-case.json
Labels: PR: awaiting review, PR: author is committer, size/S

#16338 fix stacked bar in large mode.
  src/chart/bar/BarView.ts
  src/chart/bar/install.ts
  src/chart/bar/installPictorialBar.ts
  src/core/echarts.ts
  src/data/SeriesData.ts
  src/layout/barGrid.ts
  src/layout/points.ts
  src/legacy/getTextRect.ts
  src/visual/VisualMapping.ts
  src/visual/aria.ts
  test/bar-large.html
  test/bar-tooltip-performance.html
  test/gridSimple.html
Labels: PR: awaiting review, PR: author is committer, size/XL

#16340 fix(visual): fix legend modify alpha on transparent color
  src/component/legend/LegendView.ts
  test/pie-case.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16298 feat(pie/sunburst): supports configuring any one border radius.
  src/chart/helper/pieHelper.ts
  src/chart/pie/PieView.ts
  test/pie-cornerRadius.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie-cornerRadius.json
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/S

#16347 fix(tooltip): fix the page will be frozen if multiple tooltips are provided.
  src/model/Global.ts
  test/tooltip-multiple.html
Labels: PR: awaiting review, PR: author is committer, size/S

#15985 fix(radar): name being - in tooltip when name.show is false #15915
  src/component/radar/RadarView.ts
  src/coord/radar/RadarModel.ts
  src/preprocessor/helper/compatStyle.ts
  test/radar3.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16368 feat(state): add emphasis.disabled
  src/chart/bar/BarView.ts
  src/chart/bar/PictorialBarView.ts
  src/chart/boxplot/BoxplotView.ts
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/chart/funnel/FunnelView.ts
  src/chart/gauge/GaugeView.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/EffectSymbol.ts
  src/chart/helper/Line.ts
  src/chart/helper/LineDraw.ts
  src/chart/helper/Polyline.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/line/LineView.ts
  src/chart/parallel/ParallelView.ts
  src/chart/pie/PieView.ts
  src/chart/radar/RadarView.ts
  src/chart/sankey/SankeyView.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/themeRiver/ThemeRiverView.ts
  src/chart/treemap/TreemapView.ts
  src/component/helper/MapDraw.ts
  src/component/marker/MarkAreaView.ts
  src/core/echarts.ts
  src/legacy/dataSelectAction.ts
  src/model/Series.ts
  src/util/states.ts
  src/util/types.ts
  src/view/Chart.ts
  test/emphasis-disabled.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/emphasis-disabled.json
  test/runTest/actions/line-visual2.json
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/L

#16373 fix(lines): use echarts log instead of zrender log.
  src/chart/lines/linesLayout.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16376 fix: set sourceHeader=false not work, will auto find sourceHeader(#16…
  src/data/helper/sourceManager.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16372 fix(dtatsample): fix rate infinity cause range error
  src/processor/dataSample.ts
Labels: size/XS, PR: first-time contributor

#16393 test(pie): add more VRTs for pie series.
  test/pie.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie.json
Labels: PR: awaiting review, PR: author is committer, size/XS

#16394 fix(graph): fix error when symbol is none.
  src/chart/graph/GraphView.ts
  test/graph-case.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16395 fix(core): avoid error in render breaks following update
  src/core/echarts.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16400 fix(scale): fix rounding error when increase interval in align ticks calculation
  src/scale/helper.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16405 fix(dataZoom): fix shadow may not update when size changed
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16409 chore: update zrender version
  package-lock.json
  package.json
Labels: PR: awaiting review, PR: author is committer

#16410 chore: not export declarations on the extension build
  build/pre-publish.js
Labels: size/XS

#16411 fix(geo): add back geoCoord module to avoid breaking echarts-gl
  src/coord/geo/fix/geoCoord.ts
Labels: PR: awaiting review, PR: author is committer, size/M

#16413 fix(geo): fix getMap
  src/component/geo/install.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16421 tooltip中time类型的字段默认使用的12小时制展示，容易产生困惑，改成24小时制展示
  src/util/format.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16444 fix(pie): remove unused code.
  src/chart/pie/PieView.ts
Labels: PR: awaiting review, PR: author is committer, size/XS
