Repository apache/echarts, pull requests merged in 2022-10, with the labels that each got.

#17727 fix: EChartsInitOpts type error about height and width. close #17667
  src/core/echarts.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#17734 fix(pie): fix percent isn't updated after the legend is changed
  src/chart/pie/PieSeries.ts
  src/data/SeriesData.ts
  test/pie-percent.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie-percent.json
Labels: PR: author is committer, size/M, PR: doc unchanged

#17750 chore: fix spelling mistake 'unkown' to 'unknown'
  src/chart/lines/LinesSeries.ts
  src/model/Global.ts
  src/visual/style.ts
Labels: size/XS, PR: first-time contributor

#17764 chore: update deprecated Node v12 to v16 & update action dependency version
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
  .github/workflows/stale.yml
Labels: PR: author is committer, size/M

#17559 fix: incorrect dataGroupId for old data items in universalTransition
  src/animation/universalTransition.ts
  test/universalTransition2.html
Labels: PR: awaiting doc, size/M

#16767 feat(sankey): `sankey` support `edgeLabel`
  src/chart/sankey/SankeySeries.ts
  src/chart/sankey/SankeyView.ts
  src/chart/sankey/sankeyVisual.ts
  test/sankey-depth.html
Labels: PR: author is committer, size/S

#17776 chore: fix some typos
  src/animation/customGraphicTransition.ts
  src/component/dataZoom/roams.ts
  src/component/helper/MapDraw.ts
  src/coord/View.ts
  src/coord/axisHelper.ts
  src/coord/geo/GeoSVGResource.ts
  src/coord/geo/Region.ts
  src/core/Scheduler.ts
  src/data/DataStore.ts
  src/data/helper/SeriesDataSchema.ts
  src/data/helper/transform.ts
  src/export/charts.ts
  src/layout/barGrid.ts
  src/model/Component.ts
  src/model/Global.ts
  src/model/Model.ts
  src/model/OptionManager.ts
  src/model/Series.ts
  src/model/mixin/dataFormat.ts
  src/util/types.ts
  src/view/Chart.ts
  src/view/Component.ts
Labels: size/M, PR: first-time contributor, PR: doc unchanged

#17717 feat(candlestick): provide borderColorDoji option for custom doji color
  src/chart/candlestick/CandlestickSeries.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/candlestick/candlestickLayout.ts
  src/chart/candlestick/candlestickVisual.ts
  test/candlestick-doji.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#17782 chore: fix a few typos
  src/core/CoordinateSystem.ts
  src/core/Scheduler.ts
  src/core/echarts.ts
  src/core/impl.ts
  src/core/task.ts
  src/export/api.ts
  src/export/api/helper.ts
  src/model/Component.ts
  src/model/Global.ts
  src/model/OptionManager.ts
  src/model/Series.ts
  src/model/internalComponentCreator.ts
  src/scale/Interval.ts
  src/scale/Time.ts
  src/visual/VisualMapping.ts
  src/visual/aria.ts
  src/visual/helper.ts
Labels: size/L, PR: doc unchanged

#17779 chore(workflow): always install the latest nightly version of zrender when publishing nightly echarts
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  build/nightly/post.js
  build/nightly/prepare.js
Labels: PR: author is committer, size/M

#17800 fix(i18n): language code for Ukrainian is UK, not UA
  src/i18n/langUK.ts
Labels: size/XS, PR: doc unchanged

#17611 feat: multiple level drill down support for universalTransition
  src/animation/universalTransition.ts
  src/util/types.ts
  test/universalTransition-multiLevelDrillDown.html
Labels: size/L, PR: doc ready

#17812 fix(i18n): language code for Ukrainian is UK, not UA (follow-up)
  i18n/langUK-obj.js
  i18n/langUK.js
Labels: size/XS, PR: doc unchanged

#17809 fix(dataStack): zero is neither positive nor negative stack, close #1…
  src/processor/dataStack.ts
Labels: size/XS, PR: doc unchanged

#17792 fix(graph): draggable only work on force layout
  src/chart/graph/GraphView.ts
Labels: waiting-for: author, size/XS, PR: doc unchanged

#17808 fix(type): add overflow property to AxisLabelBaseOption interface. close #17363
  src/coord/axisCommonTypes.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#17461 feat(funnel): add funnel new styles #14863
  src/chart/funnel/FunnelSeries.ts
  src/chart/funnel/FunnelView.ts
  src/chart/funnel/funnelLayout.ts
  test/funnel-dynamicHeight.html
  test/funnel-showRate.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/funnel-dynamicHeight.json
  test/runTest/actions/funnel-showRate.json
Labels: PR: awaiting review, size/XL, PR: doc ready
