Repository apache/echarts, pull requests merged in 2022-03, with the labels that each got.

#16614 fix(sanky):fallback to black if color were illegal
  src/visual/VisualMapping.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16636 chore: add vote result template in the release materials
  build/source-release/prepareReleaseMaterials.js
  build/source-release/template/vote-result.tpl
Labels: PR: awaiting review, PR: author is committer, size/M

#16644 source code format
  src/chart/bar/PictorialBarSeries.ts
  src/chart/line/LineSeries.ts
  src/chart/tree/TreeView.ts
Labels: PR: awaiting review, size/XS

#16660 feat(event-tree): add `collapsed` to `tree` click event parameters
  src/chart/tree/TreeSeries.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16672 fix(OrdinalScale): fix line graph renders null value incorrectly. clo…
  src/scale/Ordinal.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16670 fix(marker): marker state not restore after blur
  src/component/marker/MarkerView.ts
  src/util/states.ts
  src/view/Component.ts
  test/markPoint.html
Labels: PR: awaiting review, PR: author is committer, size/M

#16679 fix(visualmap): add textShadowColor, make text shadow work on visualMap. close #14440
  src/component/visualMap/ContinuousView.ts
  src/component/visualMap/PiecewiseView.ts
  test/visualMap-continuous.html
  test/visualMap-pieces.html
Labels: PR: awaiting review, size/M

#16688 feat(scatter): `scale` support number
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  test/scatter.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16691 fix(dataview): fix unexpected scrollbar and outline when using default textview
  src/component/toolbox/feature/DataView.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16702 fix(toolbox): toolbox doesn't enter emphasis state when hovering on the icon.
  src/component/toolbox/ToolboxView.ts
Labels: PR: awaiting review, PR: author is committer, size/XS

#16653 fix(gauge): fix progress bar may become unexpectedly circle when value is `0` and `progress.roundCap` is enabled.
  src/chart/gauge/GaugeView.ts
  test/gauge-case.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16714 fix(heatmap): avoid the unexpected gaps when dpr is not an integer
  src/chart/heatmap/HeatmapView.ts
  test/heatmap-gap-bug.html
  test/heatmap-large.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/heatmap-gap-bug.json
Labels: PR: awaiting review, PR: author is committer, size/S

#16730 fix(dataZoom): fix the dataZoom was unexpectedly displayed at the top when data contains null values
  src/data/DataStore.ts
  test/dataZoom-feature.html
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16719 feat: allow areaStyle.origin to take number as input
  src/chart/line/LineSeries.ts
  src/chart/line/helper.ts
  test/area-origin.html
Labels: PR: awaiting review, PR: awaiting doc, size/XS, PR: first-time contributor

#16736 fix(splitLine): fix chart throws errors when `splitLine` is enabled in radius axis.
  src/component/axis/RadiusAxisView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/splitLine.json
  test/splitLine.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16704 fix(toolbox): fix toolbox title may be outside of the chart
  src/component/toolbox/ToolboxView.ts
  test/toolbox-title.html
Labels: PR: awaiting review, PR: author is committer, size/S

#16747 fix: wrong jpg instead of jpeg image export types
  src/component/toolbox/feature/SaveAsImage.ts
  src/core/echarts.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#16754 fix: CONTRIBUTING.md grammar
  CONTRIBUTING.md
Labels: PR: awaiting review, size/S, PR: first-time contributor

#16756 Merge master into release for 5.3.2
  CONTRIBUTING.md
  build/source-release/prepareReleaseMaterials.js
  build/source-release/template/vote-result.tpl
  src/chart/bar/PictorialBarSeries.ts
  src/chart/effectScatter/EffectScatterSeries.ts
  src/chart/gauge/GaugeView.ts
  src/chart/heatmap/HeatmapView.ts
  src/chart/helper/Symbol.ts
  src/chart/helper/SymbolDraw.ts
  src/chart/line/LineSeries.ts
  src/chart/line/helper.ts
  src/chart/tree/TreeSeries.ts
  src/chart/tree/TreeView.ts
  src/component/axis/RadiusAxisView.ts
  src/component/marker/MarkerView.ts
  src/component/toolbox/ToolboxView.ts
  src/component/toolbox/feature/DataView.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/component/visualMap/ContinuousView.ts
  src/component/visualMap/PiecewiseView.ts
  src/core/echarts.ts
  src/data/DataStore.ts
  src/label/labelGuideHelper.ts
  src/scale/Ordinal.ts
  src/util/states.ts
  src/view/Component.ts
  src/visual/VisualMapping.ts
  test/area-origin.html
  test/dataZoom-feature.html
  test/gauge-case.html
  test/heatmap-gap-bug.html
  test/heatmap-large.html
  test/markPoint.html
  test/pie-label.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/heatmap-gap-bug.json
  test/runTest/actions/splitLine.json
  test/scatter.html
  test/splitLine.html
  test/toolbox-title.html
  test/visualMap-continuous.html
  test/visualMap-pieces.html
Labels: PR: awaiting review, PR: author is committer, size/XL

#16764 fix(radar): fix regression bug brought by branch merging.
  src/coord/radar/RadarModel.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/radar3.json
Labels: PR: awaiting review, PR: author is committer, size/XS
