Repository apache/echarts, pull requests merged in 2022-06, with the labels that each got.

#17150 fix(geo): fix `dataToPoint` may not be working in lineGL series.
  src/coord/geo/Geo.ts
  test/linesGL-ny-appendData.html
Labels: PR: awaiting review, PR: author is committer, size/XS

#16971 fix(markLine): fix markLine label shows wrong tooltip content
  src/component/marker/MarkLineView.ts
  test/marker-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/marker-case.json
Labels: PR: awaiting review, PR: author is committer, size/XS

#16548 fix(tree): fix tree unexpected expand
  src/chart/tree/TreeView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tree-polyline.json
Labels: PR: awaiting review, size/XS, PR: first-time contributor

#17155 fix:improve PictorialBarSeriesOption
  src/chart/bar/PictorialBarSeries.ts
Labels: size/XS, PR: first-time contributor

#17181 test: update visual test cdn to be unpkg
  test/runTest/util.js
Labels: PR: awaiting review, PR: author is committer, size/XS

#17193 fix(typo): Trasition -> Transition
  src/animation/basicTransition.ts
  src/animation/customGraphicKeyframeAnimation.ts
  src/animation/customGraphicTransition.ts
  src/animation/morphTransitionHelper.ts
  src/animation/universalTransition.ts
  src/chart/bar/BarView.ts
  src/chart/boxplot/BoxplotView.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/funnel/FunnelView.ts
  src/chart/helper/Symbol.ts
  src/chart/parallel/ParallelView.ts
  src/chart/pie/PieView.ts
  src/chart/radar/RadarView.ts
  src/chart/sunburst/SunburstPiece.ts
  src/chart/themeRiver/ThemeRiverView.ts
  src/component/graphic/GraphicView.ts
  src/util/graphic.ts
Labels: size/M, PR: first-time contributor, PR: doc unchanged

#17201 chore: update pr template to improve doc control
  .github/pull_request_template.md
Labels: size/S

#17218 fix(types): fix `SunburstSeriesOption` and `TreemapSeriesOption` types
  src/chart/sunburst/SunburstSeries.ts
  src/chart/treemap/TreemapSeries.ts
Labels: size/XS, PR: doc unchanged

#17244 feat(i18n): add Ukrainian translation. close #17243
  src/i18n/langUA.ts
Labels: size/L, PR: first-time contributor, PR: doc unchanged

#17245 chore: fix publish ci on fork
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
  .github/workflows/stale.yml
Labels: PR: author is committer, size/XS

#17247 fix(line): set default z/zlevel for temporary symbol to avoid warnings.
  src/chart/line/LineView.ts
  test/line-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/line-case.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#17242 feat(treemap.breadcrumb): add `emphasis` state
  src/chart/treemap/Breadcrumb.ts
  src/chart/treemap/TreemapSeries.ts
  src/data/DataStore.ts
  src/data/Graph.ts
  src/data/Tree.ts
  src/model/Global.ts
  src/visual/VisualMapping.ts
  test/treemap-simple.html
Labels: PR: author is committer, PR: awaiting doc, size/M
