Repository apache/echarts, pull requests merged in 2023-02, with the labels that each got.

#18244 Fixed a lot of grammatical errors in CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: size/M, PR: first-time contributor

#18279 feat(i18n): add Vietnamese(vi_VN) translation
  src/i18n/langCS.ts
  src/i18n/langDE.ts
  src/i18n/langEN.ts
  src/i18n/langFR.ts
  src/i18n/langHU.ts
  src/i18n/langIT.ts
  src/i18n/langJA.ts
  src/i18n/langKO.ts
  src/i18n/langPL.ts
  src/i18n/langPT-br.ts
  src/i18n/langRO.ts
  src/i18n/langSI.ts
  src/i18n/langTR.ts
  src/i18n/langVI.ts
  src/i18n/langZH.ts
Labels: size/XL, PR: first-time contributor, PR: doc unchanged

#18276 fix(dataset): object source contains `length` breaks render
  src/data/Source.ts
  test/dataset-category.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18301 Ignore files about 'contributing' when publish to npm
  .npmignore
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18240 fix(sunburst): `radial` rotation label might upside down
  src/chart/sunburst/SunburstPiece.ts
  test/sunburst-label.html
Labels: PR: author is committer, size/XS, PR: doc ready
