Repository apache/echarts, pull requests merged in 2023-05, with the labels that each got.

#18613 fix: typo in echarts.all.ts
  src/echarts.all.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18624 fix(graph): fix graph chart can't be hidden by legend due to edgeLabel NPE
  package.json
  src/label/LabelManager.ts
  test/graph-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/graph-case.json
Labels: PR: author is committer, size/S, PR: doc unchanged

#18469 fix(axis): show last tick for single data #18453
  src/coord/Axis.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged
