Repository apache/echarts, pull requests merged in 2023-03, with the labels that each got.

#18221 <fix>(tooltip): fix alwaysShowContent doesn't work after leaving the …
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipRichContent.ts
  src/component/tooltip/TooltipView.ts
  test/tooltip-alwaysShowContent.html
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#18310 fix(type): fix `treePathInfo` is missing in the type of sunburst formatter callback
  src/chart/sunburst/SunburstSeries.ts
  src/util/types.ts
Labels: PR: author is committer, size/S, PR: doc unchanged

#18229 fix(markArea): markArea range in bar series #18130
  src/chart/bar/BaseBarSeries.ts
  src/component/marker/markerHelper.ts
  test/bar-markArea.html
  test/marker-case.html
Labels: PR: author is committer, size/M, PR: doc unchanged

#17995 fix(polar): support borderRadius for polar bars #17980
  src/chart/bar/BarSeries.ts
  src/chart/bar/BarView.ts
  src/chart/helper/sectorHelper.ts
  src/chart/pie/PieView.ts
  src/chart/sunburst/SunburstPiece.ts
  test/bar-polar-borderRadius.html
Labels: PR: awaiting review, PR: author is committer, PR: awaiting doc, size/M

#18341 fix: `sunbrust` label abnormal
  src/chart/sunburst/SunburstPiece.ts
Labels: PR: author is committer, size/XS

#17451 feat(sankey): support `trajectory` for emphasis state
  src/chart/sankey/SankeySeries.ts
  src/chart/sankey/SankeyView.ts
  src/data/Graph.ts
  test/sankey-emphasis.html
  test/sankey.html
Labels: size/M, PR: first-time contributor, PR: doc ready

#18400 fix issue 15789
  src/core/echarts.ts
  src/util/types.ts
  test/ut/spec/series/custom.test.ts
Labels: PR: revision needed, size/XS

#18222 修复：Sankey桑基图Label Value总是undefined的问题。
  src/chart/sankey/SankeyView.ts
  src/label/labelStyle.ts
  test/sankey-labelValue.html
Labels: PR: awaiting review, size/XS, PR: first-time contributor, PR: doc unchanged

#18415 chore: update KEYS
  KEYS
Labels: PR: author is committer, size/M

#18416 chore: update deprecated npm `prepublish` hook to `prepare`
  package.json
Labels: PR: author is committer, size/XS

#18425 fix(type): fix wrong type for data item value of the `parallel` series.
  src/chart/parallel/ParallelSeries.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18427 chore: update `prepublish` to `prepare` in build script
  build/build.js
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18379 fix(lines): Lines series symbolSize cannot be updated. close #18350
  src/chart/helper/Line.ts
  test/lines-symbolSize-update.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/lines-symbolSize-update.json
Labels: size/S, PR: first-time contributor, PR: doc unchanged
