Repository apache/echarts, pull requests merged in 2023-06, with the labels that each got.

#18758 fix(api): only deprecate disConnect but not disconnect
  src/core/echarts.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18813 chore: update pre commit permission
  .husky/pre-commit
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18808 fix(sunburst): normalize label rotation when decompress from matrix
  src/chart/sunburst/SunburstPiece.ts
  src/label/LabelManager.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/sunburst-label-rotate.json
  test/sunburst-label-rotate.html
Labels: size/XS, PR: doc unchanged

#18803 chore: add PR preview workflow
  .github/workflows/ci.yml
Labels: PR: author is committer, size/M, PR: doc unchanged

#18828 chore(workflow): fix wrong env variable
  .github/workflows/ci.yml
Labels: PR: author is committer, size/XS

#18829 chore(workflow): refactor pr review workflow
  .github/workflows/ci.yml
  .github/workflows/pr-preview.yml
  .github/workflows/teardown-pr-preview.yml
Labels: PR: author is committer, size/L
