Repository apache/echarts, pull requests merged in 2023-11, with the labels that each got.

#19176 fix(sunburst): label rotation flipping
  src/chart/sunburst/SunburstPiece.ts
  test/sunburst-label-align.html
  test/sunburst-label.html
Labels: PR: author is committer, size/M, PR: doc unchanged

#19265 fix(tooltip): fix potential NPE when the parent node of the tooltip element doesn't exist
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18381 feat(ssr): server-side rendering and client hydration #18334
  .github/workflows/source-release.yml
  .gitignore
  build/build.js
  build/config.js
  build/pre-publish.js
  package-lock.json
  package.json
  src/component/legend/LegendView.ts
  src/core/echarts.ts
  src/util/innerStore.ts
  ssr/client/dist/index.js
  ssr/client/dist/index.js.map
  ssr/client/src/index.ts
  test/lib/config.js
  test/ssr.html
Labels: PR: author is committer, PR: awaiting doc, size/L

#19279 feat(sampler): add min-max sampler function
  src/processor/dataSample.ts
  src/util/types.ts
  test/line-sampling.html
Labels: size/S, PR: first-time contributor, PR: doc ready

#18960 fix(line): fix line may cross in time axis when animation is enabled
  src/chart/line/LineView.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19197 feat(pictorialBar): support clip for pictorialBar series
  src/chart/bar/PictorialBarSeries.ts
  src/chart/bar/PictorialBarView.ts
  test/pictorial-single.html
Labels: PR: author is committer, size/S, PR: doc ready
