Repository apache/echarts, pull requests merged in 2023-12, with the labels that each got.

#19357 [test] Add test case for apache/echarts#19093
  test/lib/testHelper.js
  test/manual-svg-color-bug-202311.html
Labels: PR: author is committer, size/XS

#19424 Fixed the types of barMinWidth and barMaxWidth
  src/chart/bar/BaseBarSeries.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#19228 feat(label): support align for min/max labels
  src/component/axis/AxisBuilder.ts
  src/coord/axisCommonTypes.ts
  test/axis-align-lastLabel.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#19446 chore: fix typo for `useful`
  src/component/axis/AxisBuilder.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#19449 fix: Fix typo s/buidling/building/
  build/pre-publish.js
Labels: size/XS, PR: doc unchanged

#19452 chore(workflow): add a scheduled workflow to update the NOTICE year automatically
  .github/workflows/.scripts/update-notice-year.js
  .github/workflows/update-notice-year.yml
Labels: PR: author is committer, size/L, PR: doc unchanged
