Repository apache/echarts, pull requests merged in 2023-09, with the labels that each got.

#18436 feat(tooltip): add `appendTo` option to allow customizing tooltip container
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/TooltipModel.ts
  src/component/tooltip/TooltipView.ts
  test/tooltip-appendTo.html
Labels: discussion-required, PR: awaiting doc, size/M, PR: first-time contributor

#19097 fix(visualMap): fix continuous visualMap mouseover event not register except first countinous visualMap
  src/component/visualMap/ContinuousView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/visualMap-multi-continuous.json
  test/visualMap-multi-continuous.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#19103 feat(type): export `EChartsInitOpts` and more types for `echarts/core`
  src/core/echarts.ts
  src/export/core.ts
Labels: size/M, PR: first-time contributor, PR: doc unchanged

#19107 fix(i18n): enhance default language fallback
  src/core/locale.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#19076 feat(pie): add padAngle for pie
  src/chart/pie/PieSeries.ts
  src/chart/pie/pieLayout.ts
  test/pie-pad-angle.html
Labels: PR: author is committer, size/M, PR: doc ready

#19056 fix(clip): add an extra space to the clip-path width to prevent unexpected clip. close #19051
  src/chart/helper/createClipPathFromCoordSys.ts
  test/clip-line-cap.html
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#18921 fix(tooltip): fix opacity not work in tooltip marker
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/seriesFormatTooltip.ts
  src/component/tooltip/tooltipMarkup.ts
  src/model/mixin/dataFormat.ts
  src/util/format.ts
  src/util/types.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-opacity.json
  test/tooltip-opacity.html
Labels: size/M, PR: doc unchanged

#19111 Add nullables to OptionDataValue
  src/util/types.ts
Labels: size/XS, PR: first-time contributor

#19123 feat(tooltip): add dataIndex to valueFormatter callback. close #18997
  src/component/tooltip/seriesFormatTooltip.ts
  src/component/tooltip/tooltipMarkup.ts
  src/util/types.ts
  test/tooltip-valueFormatter.html
Labels: size/S, PR: doc ready

#19099 feat(polar): allow setting `angleAxis.endAngle`
  src/component/axis/AngleAxisView.ts
  src/component/axis/RadiusAxisView.ts
  src/coord/polar/AxisModel.ts
  src/coord/polar/polarCreator.ts
  test/polar-end-angle.html
Labels: size/S, PR: doc unchanged
