Repository apache/echarts, pull requests merged in 2023-10, with the labels that each got.

#19170 fix(toolbox): fix toolbox text can't apply the specified or global font style
  src/component/toolbox/ToolboxView.ts
  src/component/toolbox/featureManager.ts
  test/toolbox-textStyle.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#19174 fix(sunburst): label rotation problem when anticlockwise
  src/chart/sunburst/SunburstPiece.ts
Labels: size/M, PR: first-time contributor

#19217 fix(core): fix potential NPE when reading default init options from global object in dev environment
  src/core/echarts.ts
Labels: PR: awaiting review, size/S, PR: first-time contributor, PR: doc unchanged

#19214 feat(i18n): add Arabic(AR) translation
  src/i18n/langAR.ts
Labels: size/L, PR: first-time contributor

#19180 fix(labelLine):emphasis.labelLine not work in pie chart
  src/label/labelGuideHelper.ts
Labels: size/XS, PR: doc unchanged

#18800 fix(label): fix labelLine default style when normal state not show but other state show
  test/roseType-labeline.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/roseType-labeline.json
Labels: size/XS, PR: doc unchanged

#19239 fix(aria): series type name for custom series
  src/i18n/langAR.ts
  src/i18n/langCS.ts
  src/i18n/langDE.ts
  src/i18n/langEN.ts
  src/i18n/langES.ts
  src/i18n/langFI.ts
  src/i18n/langFR.ts
  src/i18n/langHU.ts
  src/i18n/langIT.ts
  src/i18n/langJA.ts
  src/i18n/langKO.ts
  src/i18n/langPL.ts
  src/i18n/langPT-br.ts
  src/i18n/langRO.ts
  src/i18n/langRU.ts
  src/i18n/langSI.ts
  src/i18n/langTH.ts
  src/i18n/langTR.ts
  src/i18n/langUK.ts
  src/i18n/langVI.ts
  src/i18n/langZH.ts
  src/visual/aria.ts
Labels: PR: author is committer, size/L, PR: doc unchanged

#19252 feat(i18n): add Dutch(NL) translation
  src/i18n/langNL.ts
Labels: size/L, PR: first-time contributor, PR: doc unchanged
