Repository apache/echarts, pull requests merged in 2023-04, with the labels that each got.

#18458 chore: make reproduction link required
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#18464 chore: add official editor link to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: PR: author is committer, size/XS

#18260 fix(legend): inherit legend rich text color from legend's options
  src/component/legend/LegendView.ts
  test/legend-style.html
Labels: size/XS, PR: doc unchanged

#18524 feat(axisPointer): add option to disable emphasis. close #18495
  src/component/axisPointer/AxisPointerModel.ts
  src/component/axisPointer/axisTrigger.ts
  src/component/axisPointer/modelHelper.ts
  src/util/types.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-axisPointer2.json
  test/tooltip-axisPointer2.html
Labels: size/XS, PR: first-time contributor, PR: doc ready

#18535 fix(time-format): fix yy time format
  src/util/time.ts
  test/ut/spec/util/time.test.ts
Labels: size/XS

#18525 fix(label): ellipsis was not working
  src/label/labelStyle.ts
  src/util/types.ts
  test/label-ellipsis.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18538 chore: update `jest-canvas-mock` to fix test fails in node v18
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
  package-lock.json
  package.json
Labels: PR: author is committer, size/S

#18511 fix(emphasis): fix focus self not work when item emphasis by other component
  src/util/states.ts
  test/emphasis-self.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/emphasis-self.json
Labels: size/XS, PR: doc unchanged

#18558 chore: merge `master` branch to `next` branch to fix broken nightly-next build
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
  build/build.js
  package-lock.json
  package.json
  src/chart/helper/Line.ts
  src/component/axisPointer/AxisPointerModel.ts
  src/component/axisPointer/axisTrigger.ts
  src/component/axisPointer/modelHelper.ts
  src/component/legend/LegendView.ts
  src/label/labelStyle.ts
  src/util/states.ts
  src/util/time.ts
  src/util/types.ts
  test/emphasis-self.html
  test/label-ellipsis.html
  test/legend-style.html
  test/lines-symbolSize-update.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/emphasis-self.json
  test/runTest/actions/lines-symbolSize-update.json
  test/runTest/actions/tooltip-axisPointer2.json
  test/tooltip-axisPointer2.html
  test/ut/spec/util/time.test.ts
Labels: PR: author is committer, size/M

#18575 fix(type): allow passing `null` to the parameters of `init` function
  src/core/echarts.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged
