Repository apache/echarts, pull requests merged in 2023-07, with the labels that each got.

#18834 fix(sankey): fix other state color is 'target/source/gradient'
  src/chart/sankey/SankeyView.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/sankey-emphasis-lineStyle.json
  test/sankey-emphasis-lineStyle.html
Labels: size/M, PR: doc unchanged

#18820 feat(pie): add endAngle for control pie range
  src/chart/pie/PieSeries.ts
  src/chart/pie/pieLayout.ts
  test/pie-endAngle.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/pie-endAngle.json
Labels: size/S, PR: doc ready

#18841 fix(endLabel): endLabel fail with null data #18839
  src/chart/line/LineView.ts
  test/line-endLabel.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18845 [chore] merge #18841 into release
  src/chart/line/LineView.ts
  test/line-endLabel.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18862 chore: fix a typo in `core/echarts.ts`
  src/core/echarts.ts
Labels: size/XS, PR: first-time contributor

#18867 fix(scatter): fix edge scatter may be unexpectedly clipped due to tiny offset
  src/chart/scatter/ScatterView.ts
  src/coord/CoordinateSystem.ts
  src/coord/cartesian/Cartesian2D.ts
  test/clip.html
  test/clip2.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/clip2.json
Labels: PR: author is committer, size/S, PR: doc unchanged
