Repository apache/echarts, pull requests merged in 2024-10, with the labels that each got.

#20396 fix(theme): fix legend page text color in dark mode
  src/theme/dark.ts
  test/legend.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20399 feat(sunburst): add new emphasis focus strategy `'relative'` for highlighting ancestor and descendant nodes
  src/chart/sunburst/SunburstPiece.ts
  src/chart/sunburst/SunburstSeries.ts
  test/sunburst-emphasis-focus.html
Labels: PR: awaiting doc, size/XS

#20249 fix(visualMap): handle label collides with horizontal size visualMap
  src/component/visualMap/ContinuousView.ts
  test/visualMap-continuous.html
  test/visualMap-layout.html
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#20435 fix(tooltip): fix potential NPE when setting option with `notMerge` strategy
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor, PR: doc unchanged

#20315 fix(sample): fix minmax sampling behaviour
  src/data/DataStore.ts
  src/data/SeriesData.ts
  src/processor/dataSample.ts
Labels: size/L, PR: doc unchanged

#20398 fix(tooltip): Tooltip textStyle lineHeight does not work in default
  src/component/tooltip/TooltipHTMLContent.ts
  src/component/tooltip/tooltipMarkup.ts
  test/tooltip-textStyle-lineHeight.html
Labels: size/S, PR: doc unchanged
