Repository apache/echarts, pull requests merged in 2024-09, with the labels that each got.

#20312 feat(i18n): add Persian(FA) translation
  src/i18n/langFA.ts
Labels: PR: awaiting review, size/L, PR: first-time contributor, PR: doc unchanged

#20226 feat(custom): reusable custom series
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/chart/custom/customSeriesRegister.ts
  src/core/echarts.ts
  src/model/Global.ts
  test/custom-register.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#20313 fix(roam): fix RoamControllerHost importing path
  src/chart/treemap/TreemapView.ts
Labels: PR: awaiting review, PR: author is committer, size/XS, PR: doc unchanged

#20304 feat(dataZoom): change moveHandler cursor icon to move
  src/chart/gauge/GaugeView.ts
  src/component/dataZoom/SliderZoomView.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#20348 feat(i18n): improve pt-BR translation
  src/i18n/langPT-br.ts
Labels: size/S, PR: doc unchanged

#20329 feat(custom): use installer for reusable custom series
  src/extension.ts
Labels: PR: author is committer, size/XS

#20324 fix(boxplot) correctly handle series.encode with category axis
  src/chart/helper/whiskerBoxCommon.ts
  test/boxplot-category.html
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#20370 Fix 20363
  src/coord/polar/Polar.ts
  test/clip.html
Labels: size/XS, PR: doc unchanged

#20380 fix(sankey): avoid throwing errors when the `links` / `nodes` / `levels` option is undefined
  src/chart/sankey/SankeySeries.ts
  test/sankey.html
Labels: size/S, PR: doc unchanged

#20300 fix(pictorialBar): symbol should not flip with zero data
  src/chart/bar/PictorialBarView.ts
  test/pictorial-zero-value.html
Labels: PR: author is committer, size/XS, PR: doc unchanged
