Repository apache/echarts, pull requests merged in 2024-05, with the labels that each got.

#19892 fix(aria): avoid throwing error in SSR mode (#19191)
  src/visual/aria.ts
  test/node/ssr.js
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#19888 feat(time): add meridian template {a}/{A}
  src/util/time.ts
  test/ut/spec/util/time.test.ts
Labels: PR: awaiting doc, size/XS, PR: first-time contributor

#19901 fix(series): avoid NPE caused by `seriesData.getLinkedData`
  src/model/Series.ts
  test/graph-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/graph-case.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19898 fix(marker): fix marker label formatter can't get series information
  src/component/marker/MarkerModel.ts
  test/markPoint.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#19763 feat(sankey): Add sankey chart itemStyle.borderRadius support.
  src/chart/sankey/SankeyView.ts
  src/util/types.ts
  test/sankey-borderRadius.html
Labels: PR: awaiting doc, size/XS, PR: first-time contributor

#17078 feat: barSeries.startValue added
  src/chart/bar/BarSeries.ts
  src/coord/axisCommonTypes.ts
  src/coord/scaleRawExtentInfo.ts
  src/layout/barGrid.ts
  src/layout/barPolar.ts
  test/bar-startValue.html
Labels: PR: awaiting doc, size/M
