Repository apache/echarts, pull requests merged in 2024-01, with the labels that each got.

#19454 chore(workflow): fix timezone error when getting new year by `new Date`
  .github/workflows/.scripts/update-notice-year.js
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19461 fix(ssr): remove redundant SVG attributes with `undefined` value
  src/core/echarts.ts
  src/util/innerStore.ts
  test/svg-ssr.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#19473 chore: fix some typos
  build/config.js
  build/pre-publish.js
  src/data/helper/sourceHelper.ts
Labels: size/XS, PR: doc unchanged

#19474 chore(workflow): update actions/checkout in workflows to v4
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
Labels: size/S, PR: doc unchanged

#19476 chore(workflow): update actions/setup-node in workflows to v4
  .github/workflows/ci.yml
  .github/workflows/nightly-next.yml
  .github/workflows/nightly.yml
  .github/workflows/source-release.yml
Labels: size/S

#19499 Fix ValueAxisBaseOption doc comment
  src/coord/axisCommonTypes.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#19512 chore: ignore ssr src when release npm
  .npmignore
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19514 fix(graph): fix force layout iteration timer doesn't stop after disposing the chart
  src/chart/graph/GraphView.ts
  test/graph-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/graph-case.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19516 fix(marker): fix markArea position when axis is with `alignWithLabel`
  src/chart/bar/BaseBarSeries.ts
  test/markArea.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#18786 chore: merge `next` branch into `master`
  src/animation/universalTransition.ts
  src/util/types.ts
  test/universalTransition-multiLevelDrillDown.html
Labels: PR: author is committer, size/L

#19526 refactor(util): import `liftColor` function from zrender
  src/util/states.ts
Labels: PR: author is committer, size/M, PR: doc unchanged

#19513 feat: change to default ESM package. For developer testing and node usage in customization module scenario.
  .eslintrc-common.yaml
  .gitignore
  build/package.json
  build/pre-publish.js
  build/template/ssr/client/index.d.ts
  build/template/ssr/client/index.js
  dist/package.json
  i18n/package.json
  package.json
  ssr/client/dist/index.js
  ssr/client/dist/index.js.map
  ssr/client/dist/package.json
  ssr/client/src/.eslintrc.yaml
  ssr/client/src/index.ts
  test/package.json
  test/ssr.html
  theme/package.json
  tsconfig.json
Labels: PR: author is committer, size/L

#19543 Fix package.json exports
  build/pre-publish.js
  package.README.md
  package.json
Labels: PR: author is committer, size/L

#19558 Revert "fix(tooltip): fix opacity not work in tooltip marker"
  src/component/tooltip/TooltipView.ts
  src/component/tooltip/seriesFormatTooltip.ts
  src/component/tooltip/tooltipMarkup.ts
  src/model/mixin/dataFormat.ts
  src/util/format.ts
  src/util/types.ts
  test/runTest/actions/__meta__.json
  test/runTest/actions/tooltip-opacity.json
  test/tooltip-opacity.html
Labels: PR: author is committer, size/M

#19549 fix(ssr): hovering legend items should not trigger tooltip
  src/component/legend/LegendView.ts
  src/component/tooltip/TooltipView.ts
  src/core/echarts.ts
Labels: PR: author is committer, size/M, PR: doc unchanged

#19567 chore: add source release debug file
  .github/workflows/source-release-debug.yml
Labels: PR: author is committer, size/L, PR: doc unchanged

#19568 fix(test): rename `jest.config.js` to `jest.config.cjs` to fix jest error
  package.json
  test/ut/jest.config.cjs
Labels: PR: awaiting review, PR: author is committer, size/XS

#19569 chore: revert #19567 "chore: add source release debug file"
  .github/workflows/source-release-debug.yml
Labels: PR: author is committer, size/L

#19577 chore: add a key
  KEYS
Labels: PR: author is committer, size/M
