Repository apache/echarts, pull requests merged in 2024-07, with the labels that each got.

#20123 chore: enable prompt to use typescript from workspace
  .vscode/settings.json
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20144 chore(workflow): fix pr-preview workflow
  .github/workflows/pr-preview.yml
Labels: PR: author is committer, size/XS

#20129 fix(legend): fix legend action is not isolated from other legend components
  src/component/legend/LegendView.ts
  src/component/legend/legendAction.ts
  test/legend-action.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/legend-action.json
Labels: PR: author is committer, PR: awaiting doc, size/M

#20105 fix(candlestick): add back missing support for non-normal states since v5.0.0
  src/chart/candlestick/CandlestickSeries.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/candlestick/candlestickVisual.ts
  test/candlestick-case.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/candlestick-case.json
Labels: PR: author is committer, size/M, PR: doc ready

#20161 perf(line): reduce runtime memory cost
  src/chart/line/LineView.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20114 feature(axis): add showMin/MaxLine to splitline in coordinate axis
  src/component/axis/CartesianAxisView.ts
  src/coord/Axis.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  test/axis-splitLine.html
Labels: PR: awaiting doc, size/S

#20074 fix(pie): fix some labels may not show
  src/chart/pie/labelLayout.ts
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#20194 fix(axis): fix ticks overflowing grid area with dataZoom
  src/coord/axisTickLabelBuilder.ts
  test/axis-customTicks.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20113 feature(treemap): add custom cursor properties for treemap
  src/chart/treemap/TreemapSeries.ts
  src/chart/treemap/TreemapView.ts
  test/treemap-cursor.html
Labels: PR: awaiting doc, size/XS
