Repository apache/echarts, pull requests merged in 2024-02, with the labels that each got.

#19593 Fix: esm issue
  build/build.js
  build/config.js
  package.README.md
  package.json
Labels: PR: author is committer, size/M

#19620 fix(toolbox): use `typeof` operator rather than `isFunction` util to detect if `MouseEvent` object is supported
  src/component/toolbox/feature/SaveAsImage.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19373 Update dataset-layout.html
  test/dataset-layout.html
Labels: size/XS, PR: first-time contributor
