Repository apache/echarts, pull requests merged in 2024-06, with the labels that each got.

#18304 feat(treemap): add scaleLimit to limit the zooming. close #14599
  src/chart/treemap/TreemapSeries.ts
  src/chart/treemap/TreemapView.ts
  test/treemap-scaleLimit.html
Labels: PR: awaiting doc, size/M, PR: first-time contributor

#20030 Fix that in users' .d.ts `import('echarts/types/dist/shared')` can not visit `'echarts/types/dist/shared.d.ts'` since v5.5.0
  package.README.md
  package.json
Labels: PR: author is committer, size/S

#20020 test(treemap): update test case for #18304
  test/runTest/actions/__meta__.json
  test/runTest/actions/treemap-scaleLimit.json
  test/treemap-scaleLimit.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#19919 feat(axis): custom axis tick/label positions
  src/coord/axisCommonTypes.ts
  src/coord/axisTickLabelBuilder.ts
  test/axis-customTicks.html
Labels: PR: author is committer, size/M

#20037 Merge master to release for v5.6.0
  .github/workflows/ci.yml
  .github/workflows/pr-preview.yml
  .github/workflows/source-release.yml
  .github/workflows/stale.yml
  .npmignore
  build/testDts.js
  package-lock.json
  package.README.md
  package.json
  src/chart/bar/BarSeries.ts
  src/chart/pie/PieView.ts
  src/chart/pie/pieLayout.ts
  src/chart/sankey/SankeyView.ts
  src/chart/treemap/TreemapSeries.ts
  src/chart/treemap/TreemapView.ts
  src/component/helper/MapDraw.ts
  src/component/marker/MarkerModel.ts
  src/component/toolbox/feature/SaveAsImage.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisTickLabelBuilder.ts
  src/coord/scaleRawExtentInfo.ts
  src/data/helper/dataValueHelper.ts
  src/data/helper/sourceHelper.ts
  src/layout/barGrid.ts
  src/layout/barPolar.ts
  src/model/Series.ts
  src/util/time.ts
  src/util/types.ts
  src/visual/aria.ts
  test/axis-customTicks.html
  test/bar-startValue.html
  test/dataset-layout.html
  test/graph-case.html
  test/map-china.html
  test/markPoint.html
  test/node/ssr.js
  test/pie-endAngle.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/graph-case.json
  test/runTest/actions/pie-endAngle.json
  test/runTest/actions/treemap-scaleLimit.json
  test/sankey-borderRadius.html
  test/treemap-scaleLimit.html
  test/ut/spec/util/time.test.ts
Labels: PR: author is committer, size/L

#20051 chore(workflow): use forked workflow deps for timely update
  .github/workflows/pr-preview.yml
  .github/workflows/teardown-pr-preview.yml
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20050 feat: add role region to div tag when aria: true
  src/visual/aria.ts
Labels: PR: awaiting doc, size/XS, PR: first-time contributor

#20043 fix: clipping in custom series off by pixel#19993
  src/chart/helper/createClipPathFromCoordSys.ts
  test/clip-custom.html
Labels: size/XS, PR: doc unchanged
