Repository apache/echarts, pull requests merged in 2024-08, with the labels that each got.

#20218 feat(aria): allows excluding data in aria-label
  src/util/types.ts
  src/visual/aria.ts
  test/ut/spec/series/aria-columns-exclude.test.ts
Labels: PR: awaiting doc, size/XS

#20227 feat(i18n): add Swedish(SV) translation
  src/i18n/langSV.ts
Labels: size/L, PR: first-time contributor

#19534 Fix 9265: Axis names overlap with labels
  src/component/axis/AxisBuilder.ts
  src/coord/axisHelper.ts
  src/coord/cartesian/AxisModel.ts
  src/coord/cartesian/Grid.ts
  test/axis-containLabelAndName.html
Labels: size/L, PR: first-time contributor, PR: doc ready

#20246 fix(time): fix bar bandWidth with inversed time axis
  src/coord/axisHelper.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20252 Merge master into next
  .github/workflows/pr-preview.yml
  .vscode/settings.json
  src/chart/candlestick/CandlestickSeries.ts
  src/chart/candlestick/CandlestickView.ts
  src/chart/candlestick/candlestickVisual.ts
  src/chart/line/LineView.ts
  src/chart/pie/labelLayout.ts
  src/chart/treemap/TreemapSeries.ts
  src/chart/treemap/TreemapView.ts
  src/component/axis/CartesianAxisView.ts
  src/component/legend/LegendView.ts
  src/component/legend/legendAction.ts
  src/coord/Axis.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  src/coord/axisHelper.ts
  src/coord/axisTickLabelBuilder.ts
  src/i18n/langSV.ts
  src/util/types.ts
  src/visual/aria.ts
  test/axis-customTicks.html
  test/axis-splitLine.html
  test/candlestick-case.html
  test/legend-action.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/candlestick-case.json
  test/runTest/actions/legend-action.json
  test/runTest/package-lock.json
  test/treemap-cursor.html
  test/ut/spec/series/aria-columns-exclude.test.ts
Labels: PR: author is committer, size/L, PR: doc unchanged

#20276 fix(gauge): fix z2 is negative when maxVal is negative
  src/chart/gauge/GaugeView.ts
Labels: size/XS
