Repository apache/echarts, pull requests merged in 2024-12, with the labels that each got.

#20557 fix(pictorial): fix zero value flipping for different axes
  src/chart/bar/PictorialBarView.ts
  test/pictorial-zero-value.html
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20561 feat(geo): support styling region in original GeoJSON data
  src/component/helper/MapDraw.ts
  src/coord/geo/Region.ts
  test/geo-map.html
Labels: PR: author is committer, PR: awaiting doc, size/S

#20564 feat(geo): support styling region in original GeoJSON data
  src/chart/map/MapSeries.ts
  src/component/helper/MapDraw.ts
  src/coord/geo/GeoModel.ts
  src/coord/geo/Region.ts
  src/coord/geo/geoCreator.ts
  src/data/SeriesData.ts
  test/geo-map.html
  test/map-nested.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#20566 feat(map): support `regions[].silent` and update map data in tests
  src/chart/map/MapSeries.ts
  src/component/helper/MapDraw.ts
  src/coord/geo/GeoModel.ts
  src/coord/geo/geoCreator.ts
  test/brush.html
  test/data/map/js/china.js
  test/data/map/json/china-cities.json
  test/data/map/json/china-new.json
  test/data/map/json/china.json
  test/dataZoom-geo.html
  test/dataset-charts.html
  test/effectScatter.html
  test/geo-data-stream.html
  test/geo-lines.html
  test/geo-map.html
  test/geo-random-stream.html
  test/geo-update.html
  test/geoLine.html
  test/geoScatter.html
  test/heatmap-geo.html
  test/heatmap-map.html
  test/lines-remove.html
  test/lines-symbol.html
  test/map-china.html
  test/map-contour.html
  test/map-default.html
  test/map-locate.html
  test/map-projection.html
  test/map.html
  test/pie-coordinate-system.html
  test/scatter-random-stream-fix-axis.html
  test/scatter-weibo.html
  test/touch-slide.html
  test/visualMap-pieces.html
  test/visualMap-special-case.html
Labels: PR: author is committer, size/S, PR: doc unchanged
