Repository apache/echarts, pull requests merged in 2024-11, with the labels that each got.

#20092 fix(line): fix areaStyle skewing in stepped line series and incorrect connectNull behavior
  src/chart/line/LineView.ts
  test/line-step.html
Labels: PR: author is committer, size/M, PR: doc unchanged

#20082 feat(dataZoom): new option handleLabelShow
  src/component/dataZoom/SliderZoomModel.ts
  src/component/dataZoom/SliderZoomView.ts
  test/dataZoom-handleLabelShow.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#20485 Relax tslib requirement specifier
  package-lock.json
  package.json
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#20465 fix(BarView): borderColor hides bar color with large data. close #18185
  src/chart/bar/BarView.ts
  test/bar-large-border-fill.html
Labels: size/XS, PR: first-time contributor, PR: doc unchanged

#20491 fix(type): markLine `symbolOffset` can be a 2d array for both symbols
  src/component/marker/MarkLineModel.ts
Labels: PR: author is committer, size/XS, PR: doc ready

#20492 feat(calendar): add `silent` option for `dayLabel`/`monthLabel`/`yearLabel`
  src/component/calendar/CalendarView.ts
  test/calendar-simple.html
Labels: PR: author is committer, PR: awaiting doc, size/S

#20534 fix(data): fix potential NPE in the `SeriesData#rawIndexOf` function
  src/data/SeriesData.ts
Labels: size/XS

#16315 feat(axis): support tooltip for axis label
  package-lock.json
  package.json
  src/component/axis/AxisBuilder.ts
  test/axisLabel.html
Labels: PR: author is committer, size/S

#20484 test(aria): fix test case of #20218
  test/ut/spec/series/aria-columns-exclude.test.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20551 fix(visualMap): cursor is pointer on selectedMode=false
  src/component/visualMap/PiecewiseView.ts
  test/visualMap-selectMode.html
Labels: size/S, PR: doc unchanged
