Repository apache/echarts, pull requests merged in 2025-03, with the labels that each got.

#20800 fix(title): title text style width type should not include string #20799
  src/component/title/install.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20782 feat(marker): markPoint markLine markArea add z2 option to support change level
  src/chart/helper/Line.ts
  src/chart/helper/Symbol.ts
  src/component/marker/MarkAreaModel.ts
  src/component/marker/MarkAreaView.ts
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkLineView.ts
  src/component/marker/MarkPointModel.ts
  src/component/marker/MarkPointView.ts
  src/data/SeriesData.ts
  test/marker-z2.html
Labels: PR: author is committer, PR: awaiting doc, size/M

#20814 fix(dataZoom): restrict range on brushEnd
  src/component/dataZoom/SliderZoomView.ts
Labels: size/S, PR: first-time contributor, PR: doc unchanged

#20321 (feat) Sankey roaming
  src/chart/sankey/SankeySeries.ts
  src/chart/sankey/SankeyView.ts
  src/chart/sankey/install.ts
  src/chart/tree/TreeView.ts
  src/component/helper/roamHelper.ts
  test/sankey-roam.html
Labels: PR: author is committer, PR: awaiting doc, size/L

#18164 feat(legend): legend support triggerEvent (#18144)
  src/component/legend/LegendModel.ts
  src/component/legend/LegendView.ts
  test/legend-action.html
Labels: PR: awaiting doc, size/M

#20874 fix: add css for test helper new added range input and select input.
  test/lib/reset.css
Labels: PR: awaiting review, PR: author is committer, size/XS

#20877 (test): enhance testHelper to support range input in select.
  test/lib/reset.css
  test/lib/testHelper.js
Labels: PR: awaiting review, PR: author is committer, size/XS

#20884 Fix visual test and enhance testHelper.
  test/lib/reset.css
  test/lib/testHelper.js
  test/runTest/cli.js
  test/runTest/recorder/recorder.js
Labels: PR: awaiting review, PR: author is committer, size/XS
