Repository apache/echarts, pull requests merged in 2025-05, with the labels that each got.

#20961 fix(visualMap): fix some text style can't work on visualMap
  src/component/visualMap/ContinuousView.ts
  src/component/visualMap/PiecewiseView.ts
  test/visualMap-pieces.html
Labels: PR: awaiting review, PR: author is committer, size/S, PR: doc unchanged

#20977 fix(label): fix label rich style does not inherit the plain label style
  src/label/labelStyle.ts
  test/rich-inherit-plain-label.html
  test/richText.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/rich-inherit-plain-label.json
Labels: PR: author is committer, PR: awaiting doc, size/S

#16978 fix(dataZoom): render data not equally distributed. close #16924 #15921
  src/component/dataZoom/SliderZoomView.ts
Labels: size/M

#20987 fix(tooltip): fix style coord transform markers are not removed after the tooltip is disposed
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: author is committer, size/S, PR: doc unchanged
