Repository apache/echarts, pull requests merged in 2025-04, with the labels that each got.

#20887 misc: fix spelling
  build/source-release/prepareReleaseMaterials.js
  test/custom-feature.html
  test/legend.html
  test/touch-test.html
Labels: PR: author is committer, size/XS, PR: first-time contributor

#20760 fix(svg): remove SVG support check in `getSvgDataURL`
  src/core/echarts.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20522 feat: Chord charts
  src/chart/chord/ChordEdge.ts
  src/chart/chord/ChordPiece.ts
  src/chart/chord/ChordSeries.ts
  src/chart/chord/ChordView.ts
  src/chart/chord/chordLayout.ts
  src/chart/chord/install.ts
  src/chart/funnel/funnelLayout.ts
  src/chart/pie/PieView.ts
  src/chart/pie/pieLayout.ts
  src/chart/sankey/sankeyLayout.ts
  src/chart/tree/layoutHelper.ts
  src/chart/tree/treeLayout.ts
  src/echarts.all.ts
  src/export/charts.ts
  src/export/option.ts
  src/model/Global.ts
  src/util/layout.ts
  test/chord.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/chord.json
  test/runTest/client/client.js
Labels: PR: author is committer, PR: awaiting doc, size/XXL

#20907 feat(legend): legend support `triggerEvent` option
  src/component/legend/LegendView.ts
Labels: PR: awaiting review, PR: author is committer, size/S, PR: doc unchanged

#20906 fix(pie): fix labelLine may be not removed and cause error when single label position is not in outside
  src/chart/pie/PieView.ts
  test/pie-label.html
Labels: PR: awaiting review, PR: author is committer, size/XS, PR: doc unchanged

#20901 fix(bar): remove unused `startValue` option from the `BarSeriesOption` interface
  src/chart/bar/BarSeries.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20920 fix(custom): fix potential NPE when applying leave transition
  src/animation/customGraphicTransition.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#20447 feat(custom): support disableTooltip for custom series
  src/chart/custom/CustomSeries.ts
  src/chart/custom/CustomView.ts
  src/component/tooltip/TooltipView.ts
  src/util/types.ts
  test/custom-feature.html
Labels: PR: revision needed, PR: author is committer, PR: awaiting doc, size/S

#19941 feat(scatter): jittering for category data
  src/chart/scatter/install.ts
  src/chart/scatter/jitterLayout.ts
  src/coord/axisCommonTypes.ts
  src/coord/axisDefault.ts
  src/coord/single/AxisModel.ts
  src/echarts.all.ts
  src/export/features.ts
  src/util/jitter.ts
  test/scatter-jitter.html
  test/violin.html
Labels: PR: author is committer, size/L, PR: doc ready
