Repository apache/echarts, pull requests merged in 2025-06, with the labels that each got.

#21016 fix(rich-text-inherit-plain)
  src/label/labelStyle.ts
  test/rich-inherit-plain-label.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/rich-inherit-plain-label.json
Labels: PR: author is committer, size/M

#20777 fix(axis):null value item on category axis should be able to show tooltip
  src/scale/Ordinal.ts
  test/axis-dataset-null.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/axis-dataset-null.json
Labels: size/XS, PR: doc unchanged

#20998 feat(stack): able to reverse the stack order
  src/processor/dataStack.ts
  src/util/types.ts
  test/bar-stack-reverse.html
Labels: PR: awaiting review, PR: revision needed, PR: awaiting doc, size/M

#21040 fix(buildPath): revert checking buildPath
  src/chart/custom/CustomView.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#21042 fix(marker): fix bug of #20166
  src/component/marker/MarkPointView.ts
  src/component/marker/markerHelper.ts
  test/dataZoom-action.html
Labels: PR: author is committer, size/S, PR: doc unchanged

#21043 fix(dataZoom): fix dataZoom for single data
  src/component/dataZoom/SliderZoomView.ts
  test/dataZoom-timeAxis.html
Labels: size/XS

#21046 chore: merge master into v6
  src/component/dataZoom/SliderZoomView.ts
  src/processor/dataStack.ts
  src/scale/Ordinal.ts
  src/util/types.ts
  test/axis-dataset-null.html
  test/bar-stack-reverse.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/axis-dataset-null.json
Labels: PR: awaiting review, PR: author is committer, size/M, PR: doc unchanged

#21045 fix(dataZoom): fix the case when first value is NaN, relates to #16978
  src/component/dataZoom/SliderZoomView.ts
Labels: PR: author is committer, size/XS, PR: doc unchanged

#21050 chore: use zrender#next and remove unused import
  package-lock.json
  package.json
  src/util/model.ts
Labels: size/XS

#21066 test: clarify mktest tpl.
  test/build/mktest-tpl.html
Labels: PR: awaiting review, PR: author is committer, size/XS
