Repository apache/echarts, pull requests merged in 2025-09, with the labels that each got.

#21219 fix(dataset): wrong area when dimension name is empty string
  src/chart/line/LineView.ts
  test/line-area-empty-dimension-name.html
Labels: size/XS, PR: doc unchanged

#21224 feat(gauge): progress.color supports 'auto'
  src/chart/gauge/GaugeView.ts
  test/gauge-progress.html
Labels: PR: awaiting doc, size/XS, PR: first-time contributor

#21196 fix(dataZoom): fix wrong position of the dataZoom when the series has only one data point
  src/component/dataZoom/SliderZoomView.ts
  test/dataZoom-single-datapoint.html
Labels: size/XS, PR: first-time contributor, PR: doc unchanged, PR: regression fix
