Repository apache/echarts, pull requests merged in 2025-07, with the labels that each got.

#21087 fix(tooltip): fix potential memory leakage by explicitly unbinding event listeners
  src/component/tooltip/TooltipHTMLContent.ts
Labels: PR: awaiting review, size/XS, PR: first-time contributor, PR: doc unchanged

#21108 Fix matrix label API
  src/component/matrix/MatrixView.ts
  src/coord/matrix/MatrixBodyCorner.ts
  src/coord/matrix/MatrixModel.ts
  src/coord/matrix/matrixCoordHelper.ts
  src/util/model.ts
  test/matrix.html
  test/matrix2.html
  test/matrix3.html
  test/matrix4.html
  test/matrix_application.html
  test/runTest/actions/matrix2.json
  test/runTest/actions/matrix4.json
  test/runTest/marks/matrix.json
Labels: size/M

#21106 test(matrix): add matrix mbti
  test/matrix-mbti.html
Labels: size/XS

#21107 fix(axis-log): Enable ticks under 1e-10, fixes #21099
  src/scale/Log.ts
  test/logScale.html
Labels: size/XS

#21104 fix(visualMap): fix range comparison
  src/component/visualMap/ContinuousModel.ts
Labels: size/XS

#21114 fix(visualMap): fix dark mode should not provide inRange
  src/theme/dark.ts
Labels: size/XS

#21120 fix(logScale): Fix incorrect rounding usage, and support data with big negative exponent.
  src/scale/Log.ts
  test/logScale.html
  test/runTest/actions/__meta__.json
  test/runTest/actions/logScale.json
Labels: size/XS

#21119 feat(i18n): add Greek locale. Closes #21118
  src/i18n/langEL.ts
  test/lang.html
Labels: size/L

#21081 fix: add symbolPath opacity. close #21074
  src/chart/radar/RadarView.ts
  test/radar.html
Labels: PR: awaiting review, size/S, PR: first-time contributor, PR: doc unchanged

#21117 feat(marker): markPoint markLine markArea support z option
  src/component/marker/MarkLineModel.ts
  src/component/marker/MarkerModel.ts
  src/component/marker/MarkerView.ts
  src/data/SeriesData.ts
  test/marker-z-z2.html
  test/marker-z2.html
  test/runTest/marks/marker-z-z2.json
Labels: size/M

#21138 test: revert incorrect modification introduced in c4481090e1a228c883bede102599fc14962e556a
  test/check-build.html
Labels: size/XS
